/**
 * @agent-core/agent-provisioning — per-agent DSH_HOME provisioning.
 *
 * PRODUCTION_RUNTIME_V1 extraction of the home-provisioning half of the old
 * `scripts/demo-home.mjs` (which stays as a thin backwards-compatible shim
 * for the demo/benchmark path): the Router / Control Plane spawns every
 * Agent through `dsh --profile <agentProfile>`, and THIS module is the
 * single place that makes such a spawn self-sufficient — no verification
 * driver or operator may be needed to pre-provision an agent home.
 *
 * The profile table (`AGENT_PROFILE_DEFS`) is the SINGLE mapping from a
 * profile name to the repo profile dir + the out-of-tree plugin farm links
 * its composition needs. Production runtimes use `agent-core-production`
 * (packages/production-runtime passes it explicitly); the legacy demo /
 * integration profiles remain available for the demo and acceptance paths.
 *
 * The module is deliberately dependency-free (node builtins only) so the
 * Router can import it directly from the control plane composition.
 */

import {
  copyFileSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync,
} from 'node:fs'
import { spawnSync } from 'node:child_process'
import { homedir } from 'node:os'
import { basename, dirname, isAbsolute, join, resolve } from 'node:path'
import {
  assertSameDomainCredentialFile,
  canonicalOpenAICodexCredentialFileFor,
  deploymentRootOfAgentHome,
  persistOpenAICodexCredentialFile,
  CANONICAL_DEFAULT_MODEL_ROUTE,
} from './shared-codex.js'
import { installedArtifactMatches, installedPluginVersion, stampInstalledArtifact, verifyPluginInputs, resolvePluginPeerLinks } from './plugin-artifact.js'
import { ensureSymlink } from './ensure-symlink.js'
import { REPO, ensureRepoCoreBridge, provisionProfileWorkspaceLinks } from './repo-core-bridge.js'
export { REPO, ensureRepoCoreBridge }

export {
  assertOAuthCredentialBoundary,
  assertSameDomainCredentialFile,
  canonicalOpenAICodexCredentialFileFor,
  deploymentRootOfAgentHome,
  CANONICAL_OPENAI_CODEX_CREDENTIAL_FILE,
  persistOpenAICodexCredentialFile,
} from './shared-codex.js'

/**
 * Resolve the deepseek-harness checkout (the `dsh` CLI the Router spawns
 * agents through). Env override first; then the sibling-of-repo default,
 * aware that a git WORKTREE root is one level deeper than the main checkout
 * (the harness stays a sibling of the MAIN repo, not of the worktree).
 */
export function resolveHarnessRoot() {
  if (process.env.DSH_HARNESS_ROOT) return process.env.DSH_HARNESS_ROOT
  const mainRepo = REPO.split('/.worktree/')[0] ?? REPO
  const candidates = [
    resolve(mainRepo, '../../github/deepseek-harness'),   // main-tree layout
    resolve(REPO, '../../github/deepseek-harness'),       // worktree layout (same repo, one level deeper)
  ]
  for (const candidate of candidates) {
    if (existsSync(join(candidate, 'apps', 'cli', 'lib', 'bin.js'))) return candidate
  }
  return candidates[0]
}

/** Backwards-compatible alias (demo-home called it dshRoot). */
export function dshRoot() {
  return resolveHarnessRoot()
}

/** The dsh CLI entry the agent processes boot through. */
export function cliBin() {
  const cli = join(resolveHarnessRoot(), 'apps/cli/lib/bin.js')
  if (!existsSync(cli)) {
    throw new Error(`dsh CLI not found at ${cli}; set DSH_HARNESS_ROOT to the deepseek-harness checkout`)
  }
  return cli
}

function provisioningError(code, message, cause) {
  return Object.assign(new Error(`agent-provisioning: ${message}`, { cause }), { code })
}

/**
 * Read the deployment-owned trusted source stamp (DEC-ACT-004). The stamp is
 * a single JSON object at the harness root with the exact key set
 * {commit, dirtyCount}: commit = 40-char lowercase hex, dirtyCount = integer
 * >= 0. It is generated by the deployment process and only ever consulted
 * when git itself is unavailable (a production harness ships without .git);
 * it is never a substitute trust surface beyond that.
 */
function readSourceStamp(harnessRoot) {
  const stampFile = join(harnessRoot, '.source-stamp')
  let stamp
  try {
    stamp = JSON.parse(readFileSync(stampFile, 'utf8'))
  } catch (cause) {
    if (cause?.code === 'ENOENT') {
      throw provisioningError('dsh_commit_mismatch', `cannot verify DSH commit under ${harnessRoot}: git unavailable and .source-stamp missing`)
    }
    throw provisioningError('dsh_commit_mismatch', `cannot verify DSH commit under ${harnessRoot}: .source-stamp is not valid JSON`, cause)
  }
  if (stamp === null || typeof stamp !== 'object' || Array.isArray(stamp)) {
    throw provisioningError('dsh_commit_mismatch', `cannot verify DSH commit under ${harnessRoot}: .source-stamp must be a single JSON object with exactly {commit, dirtyCount}`)
  }
  const keys = Object.keys(stamp).sort()
  if (keys.length !== 2 || keys[0] !== 'commit' || keys[1] !== 'dirtyCount') {
    throw provisioningError('dsh_commit_mismatch', `cannot verify DSH commit under ${harnessRoot}: .source-stamp must contain exactly {commit, dirtyCount}`)
  }
  if (typeof stamp.commit !== 'string' || !/^[0-9a-f]{40}$/u.test(stamp.commit)) {
    throw provisioningError('dsh_commit_mismatch', `cannot verify DSH commit under ${harnessRoot}: .source-stamp commit must be 40-character lowercase hex`)
  }
  if (!Number.isInteger(stamp.dirtyCount) || stamp.dirtyCount < 0) {
    throw provisioningError('dsh_commit_mismatch', `cannot verify DSH commit under ${harnessRoot}: .source-stamp dirtyCount must be an integer >= 0`)
  }
  if (stamp.dirtyCount !== 0) {
    throw provisioningError('dsh_commit_mismatch', `cannot verify DSH commit under ${harnessRoot}: .source-stamp reports dirtyCount ${stamp.dirtyCount} relative to commit ${stamp.commit} (identity is not exact)`)
  }
  return stamp
}

/**
 * Resolve the exact DSH version + source commit used by the spawned CLI.
 * Commit identity prefers git (rev-parse HEAD, dirty tree semantics
 * unchanged); ONLY when git is unavailable (no .git / rev-parse failure) does
 * the trusted deployment-owned .source-stamp take over. Commit identity is
 * never derived from the package.json version alone; all failures stay in
 * the existing dsh_commit_mismatch fail-loud family (DEC-ACT-004 iii).
 */
export function readHarnessIdentity(harnessRoot = resolveHarnessRoot()) {
  let version
  try {
    version = JSON.parse(readFileSync(join(harnessRoot, 'package.json'), 'utf8')).version
  } catch (cause) {
    throw provisioningError('dsh_version_mismatch', `cannot verify DSH version under ${harnessRoot}`, cause)
  }
  const result = spawnSync('git', ['-C', harnessRoot, 'rev-parse', 'HEAD'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  if (result.status !== 0) {
    const stamp = readSourceStamp(harnessRoot)
    return { version, commit: stamp.commit }
  }
  return { version, commit: result.stdout.trim() }
}

function atomicWriteJson(file, value) {
  const temp = `${file}.tmp-${process.pid}`
  writeFileSync(temp, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o644 })
  renameSync(temp, file)
}

function defaultPluginInstaller({ profilesRoot, plugin, version, packageArtifact, artifactBinding }) {
  if (packageArtifact !== undefined && (!isAbsolute(packageArtifact) || !existsSync(packageArtifact))) {
    throw provisioningError('plugin_missing', `local package artifact must be an existing absolute path: ${packageArtifact}`)
  }
  if (artifactBinding) {
    // The domain-bound artifact is already the complete accepted payload.
    // npm prunes its unbundled dependencies; retain the exact archive instead.
    const installedRoot = join(profilesRoot, 'node_modules', plugin)
    mkdirSync(dirname(installedRoot), { recursive: true })
    const scratch = mkdtempSync(join(dirname(installedRoot), '.exact-artifact-'))
    try {
      const unpack = spawnSync('/usr/bin/tar', ['-xzf', packageArtifact, '-C', scratch], { encoding: 'utf8' })
      const payload = join(scratch, 'package')
      if (unpack.status !== 0 || !existsSync(payload) || !lstatSync(payload).isDirectory()
        || !installedArtifactMatches(payload, packageArtifact)) {
        throw provisioningError('plugin_artifact_mismatch', `cannot unpack exact ${plugin}@${version} payload`)
      }
      const manifest = JSON.parse(readFileSync(join(payload, 'package.json'), 'utf8'))
      if (manifest.name !== plugin || manifest.version !== version) throw provisioningError('plugin_version_mismatch', 'archive package name/version differs')
      rmSync(installedRoot, { recursive: true, force: true })
      renameSync(payload, installedRoot)
    } finally { rmSync(scratch, { recursive: true, force: true }) }
    return
  }
  const result = spawnSync('npm', [
    'install', '--prefix', profilesRoot, '--no-save', '--no-package-lock', '--ignore-scripts',
    ...(packageArtifact === undefined ? [] : ['--offline', '--legacy-peer-deps']),
    packageArtifact ?? `${plugin}@${version}`,
  ], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  if (result.status !== 0) {
    throw provisioningError('plugin_missing', `failed to install exact ${plugin}@${version}`)
  }
}

// Read-only: shares precisely the normal provisioning input checks.
export function verifyPluginProvisioningInputs(requirement, options = {}) {
  return verifyPluginInputs(requirement, options, readHarnessIdentity)
}

/**
 * Install/verify one exact external bundle in this Agent's own profile farm.
 * The shared repo profile is never touched. Tests inject `pluginInstaller`
 * so ordinary automation has no npm-registry dependency.
 */
export function provisionExactProfilePlugin(home, profile, requirement, options = {}) {
  verifyPluginProvisioningInputs(requirement, { ...options, deploymentRoot: deploymentRootOfAgentHome(home) })
  const { plugin, version, sourceCommit, artifactSha256, dshVersion } = requirement
  const injectedArtifactIdentity = options.artifactIdentity
  const artifactIdentity = { version: 1, sourceCommit, artifactSha256 }
  const profilesRoot = join(home, 'profiles')
  const installedRoot = join(profilesRoot, 'node_modules', plugin)
  const installedPackage = join(profilesRoot, 'node_modules', plugin, 'package.json')
  const existingVersion = installedPluginVersion(installedPackage)
  if (existingVersion !== undefined && existingVersion !== version) {
    throw provisioningError('plugin_version_mismatch', `expected ${plugin}@${version}, resolved ${existingVersion ?? '(missing)'}`)
  }
  // Same version is insufficient: reuse only exact installed artifact bytes.
  if (!installedArtifactMatches(installedRoot, options.packageArtifact, artifactIdentity)) {
    rmSync(installedRoot, { recursive: true, force: true })
    const installer = options.pluginInstaller ?? defaultPluginInstaller
    installer({ profilesRoot, plugin, version, packageArtifact: options.packageArtifact, artifactBinding: requirement.artifactBinding })
    if (injectedArtifactIdentity !== undefined && existsSync(installedRoot)) stampInstalledArtifact(installedRoot, artifactIdentity)
  }
  if (!existsSync(installedPackage)) {
    throw provisioningError('plugin_missing', `${plugin}@${version} is not resolvable from ${profilesRoot}/node_modules`)
  }
  if (requirement.artifactBinding && JSON.parse(readFileSync(installedPackage, 'utf8')).name !== plugin) throw provisioningError('plugin_version_mismatch', 'installed archive package name differs')
  const installedVersion = installedPluginVersion(installedPackage)
  if (installedVersion !== version) {
    throw provisioningError('plugin_version_mismatch', `expected ${plugin}@${version}, resolved ${installedVersion ?? '(missing)'}`)
  }
  if (!installedArtifactMatches(installedRoot, options.packageArtifact, artifactIdentity)) {
    throw provisioningError('plugin_artifact_mismatch', `installed ${plugin}@${version} payload does not match the pinned artifact`)
  }
  stampInstalledArtifact(installedRoot, artifactIdentity)

  // External bundles declare DSH packages as peers. A local tarball install
  // intentionally uses --legacy-peer-deps so npm cannot consult the registry;
  // close those peers against the already-pinned Harness checkout instead.
  // This also prevents npm from choosing a different published DSH version.
  // GPT6_LUNA_AND_REASONING_EFFORT_V1 (ACC-G6R-002): @earendil-works/pi-ai is
  // the one exception — the frozen GPT-6 artifact identity is a DEPLOYMENT-
  // provided exact npm artifact, so a pi-ai already present in the profile
  // farm is kept and identity-checked below instead of harness-closed.
  const packageJson = JSON.parse(readFileSync(installedPackage, 'utf8'))
  const harnessRoot = options.harnessRoot ?? resolveHarnessRoot()
  for (const { source, destination } of resolvePluginPeerLinks(packageJson, profilesRoot, harnessRoot, { plugin, version, dshVersion })) ensureSymlink(source, destination)

  const profilePackageFile = join(profilesRoot, profile, 'package.json')
  const profilePackage = JSON.parse(readFileSync(profilePackageFile, 'utf8'))
  const bundles = profilePackage?.dsh?.profile?.bundles
  if (!Array.isArray(bundles)) {
    throw provisioningError('plugin_provisioning_invalid', `${profilePackageFile} has no dsh.profile.bundles array`)
  }
  if (!bundles.includes(plugin)) {
    bundles.push(plugin)
    atomicWriteJson(profilePackageFile, profilePackage)
  }
  return { plugin, version, installedPackage, profilePackageFile }
}

/** Copy a file when the source exists; never overwrite an existing target. */
function copyOnce(source, target) {
  if (!existsSync(source)) return false
  if (existsSync(target)) return true
  mkdirSync(dirname(target), { recursive: true })
  copyFileSync(source, target)
  return true
}

// DEFAULT_MODEL_ROUTING_CONFIG_V1 §4: the fresh-home child-side default is
// the canonical built-in Luna route (constant-composed, no route literal
// here). The opencode-go provider REGISTRATION block stays — OpenCode Go
// remains an explicit selectable route; registration is not selection. The
// openai-codex provider self-registers via the dsh-codex plugin mount.
const MINIMAL_SETTINGS = [
  'llm-pi-ai:',
  '  providers:',
  '    opencode-go:',
  '      apiKeyEnv: OPENCODE_GO_API_KEY',
  'agent-default-model:',
  `  provider: ${CANONICAL_DEFAULT_MODEL_ROUTE.provider}`,
  `  model: ${CANONICAL_DEFAULT_MODEL_ROUTE.model}`,
  '',
].join('\n')

/**
 * Per-agent profile definitions: profile name → repo profile dir + the
 * out-of-tree plugin farm links the profile's composition needs.
 *
 * The Router / Control Plane spawns every Agent through `dsh --profile
 * <agentProfile>`; this table is the SINGLE place that maps a profile name
 * to what must be installed into the Agent's DSH_HOME so that spawn is
 * self-sufficient (no verification-driver pre-provisioning allowed).
 *
 * - profile files are COPIES (the CLI rewrites cordis.yml inside the profile
 *   dir on every boot, so sharing one symlinked dir across agents is unsafe);
 * - farm links are SYMLINKS into the repo (additive, idempotent).
 */
export const AGENT_PROFILE_DEFS = {
  'agent-core-production': {
    repoDir: 'profile-production',
    farmLinks: {
      'bundle-demo': 'bundle-demo',
      'owner-guard': 'packages/owner-guard',
      'demo-server': 'packages/demo-server',
      'bundle-memory': 'bundle-memory',
      'agent-memory': 'packages/agent-memory',
      'bundle-agent-switch': 'bundle-agent-switch',
      'agent-switch': 'packages/agent-switch',
      'workspace-bootstrap': 'packages/workspace-bootstrap',
      // Trusted credential broker: the child composition mounts the broker
      // in relay mode (capability tools -> parent-RPC -> control-plane
      // Broker gateway). The child holds no credential/token.
      'bundle-broker': 'bundle-broker',
      'broker': 'packages/broker',
    },
  },
  'agent-core-demo': {
    repoDir: 'profile-demo',
    farmLinks: {
      'bundle-demo': 'bundle-demo',
      'owner-guard': 'packages/owner-guard',
      'demo-server': 'packages/demo-server',
    },
  },
  'agent-core-integration-agent': {
    repoDir: 'profile-integration-agent',
    farmLinks: {
      'bundle-demo': 'bundle-demo',
      'owner-guard': 'packages/owner-guard',
      'demo-server': 'packages/demo-server',
      'bundle-memory': 'bundle-memory',
      'agent-memory': 'packages/agent-memory',
      'bundle-agent-switch': 'bundle-agent-switch',
      'agent-switch': 'packages/agent-switch',
      'workspace-bootstrap': 'packages/workspace-bootstrap',
      // Trusted credential broker: the child composition mounts the broker
      // in relay mode (capability tools -> parent-RPC -> control-plane
      // Broker gateway). The child holds no credential/token.
      'bundle-broker': 'bundle-broker',
      'broker': 'packages/broker',
    },
  },
}

/**
 * Provision one agent home (idempotent). Returns the resolved home path.
 * The profile is REQUIRED and must be a known AGENT_PROFILE_DEFS entry — a
 * production spawn must never silently fall back to a default composition.
 * @param {string} home - absolute home directory (the agent's DSH_HOME).
 * @param {string} workspace - absolute working directory for the agent process.
 * @param {object} options - `{ profile, subscription?, deploymentRoot? }` — the per-agent
 *   profile to install plus an optional deployment-resolved target-only
 *   external plugin/credential requirement; unknown profiles fail loud.
 *   `deploymentRoot` (the runtime's `--root`) pins the persisted shared credentialFile
 *   reference to THAT surface's canonical store; production homes laid out as
 *   `<root>/homes/<agent>` are additionally guarded against cross-surface references
 *   even without it.
 * @returns {string} the resolved home path.
 */
export function provisionAgentHome(home, workspace, options = {}) {
  const profile = options.profile
  if (typeof profile !== 'string' || profile === '') {
    throw new TypeError('provisionAgentHome: options.profile is required (no default — the caller owns the composition choice)')
  }
  const def = AGENT_PROFILE_DEFS[profile]
  if (def === undefined) {
    throw new Error(`provisionAgentHome: unknown agent profile ${JSON.stringify(profile)} (known: ${Object.keys(AGENT_PROFILE_DEFS).join(', ')})`)
  }
  // Validate the domain binding before any home/profile/seed side effect.
  const bound = options.subscription
  if (bound?.artifactBinding) verifyPluginProvisioningInputs({ ...bound, version: bound.pluginVersion }, {
    ...options, packageArtifact: bound.packageArtifact, sourceStamp: bound.sourceStamp,
    deploymentRoot: deploymentRootOfAgentHome(home),
  })
  // A freshly provisioned Agent-owned home starts private. Existing homes are
  // never chmodded here: an operator-owned 0755 home remains a fail-loud
  // activation prerequisite rather than being mutated implicitly.
  mkdirSync(home, { recursive: true, mode: 0o700 })
  // Farm links point into the repo; the repo must expose @agent-core names
  // for transitive imports (see ensureRepoCoreBridge). Production topology
  // is deployment-owned; this call is read-only when the repo is immutable.
  ensureRepoCoreBridge()
  const settingsSource = process.env.DSH_SETTINGS_SOURCE ?? join(homedir(), '.dsh', 'settings.yaml')
  if (!copyOnce(settingsSource, join(home, 'settings.yaml'))) {
    mkdirSync(home, { recursive: true })
    if (!existsSync(join(home, 'settings.yaml'))) writeFileSync(join(home, 'settings.yaml'), MINIMAL_SETTINGS)
  }
  copyOnce(join(homedir(), '.dsh', '.credentials.yaml'), join(home, '.credentials.yaml'))

  // The agent profile (copies — the CLI rewrites cordis.yml inside it).
  const profileDir = join(home, 'profiles', profile)
  mkdirSync(profileDir, { recursive: true })
  for (const file of ['package.json', 'cordis.patch.yml']) {
    if (existsSync(join(profileDir, file))) continue
    copyFileSync(join(REPO, def.repoDir, file), join(profileDir, file))
  }

  // Install the external package BEFORE creating the local farm links: npm
  // prunes extraneous entries under node_modules, so reversing this order
  // would delete the production profile's @agent-core bundles on first use.
  if (options.subscription !== undefined) {
    const subscription = options.subscription
    provisionExactProfilePlugin(home, profile, {
      plugin: subscription.plugin,
      version: subscription.pluginVersion,
      sourceCommit: subscription.sourceCommit,
      artifactSha256: subscription.artifactSha256,
      ...(subscription.artifactBinding === undefined ? {} : { artifactBinding: subscription.artifactBinding }),
      dshVersion: subscription.dshVersion,
      dshCommit: subscription.dshCommit,
    }, {
      pluginInstaller: options.pluginInstaller,
      packageArtifact: subscription.packageArtifact,
      sourceStamp: subscription.sourceStamp,
      artifactIdentity: options.artifactIdentity,
      harnessIdentity: options.harnessIdentity,
      harnessRoot: options.harnessRoot,
    })
    const persistOptions = {
      // GPT6_LUNA_AND_REASONING_EFFORT_V1: the route's per-route reasoning
      // effort rides the SAME provisioned profile patch as the credential
      // reference, so one spawn's provisioning output is internally
      // consistent (plugin artifact + plugin config always from one route).
      reasoningEffort: subscription.reasoningEffort,
    }
    if (typeof options.deploymentRoot === 'string' && options.deploymentRoot !== '') {
      persistOptions.deploymentRoot = options.deploymentRoot
    }
    if (basename(dirname(home)) === 'homes') persistOptions.agentHome = home
    persistOpenAICodexCredentialFile(join(profileDir, 'cordis.patch.yml'), subscription.credentialFile, persistOptions)
  }

  return provisionProfileWorkspaceLinks(home, workspace, def.farmLinks)
}
