#!/usr/bin/env bash
#
# /tmp/run-svc-workflow-test-fixture-cleanup-v2.sh
#
# v2 = audited v1 + check P2b LIFETIME_FIXTURE_PATTERN_DRIFT_GATE.
# Revision of audit blocker B1 (SVC_WORKFLOW_DOGFOOD_TEST_FIXTURE_RESIDUE_V1_AUDIT,
# dsh-agent-core 344cce3): v1's P2 "fixture-pattern rows outside the allowlist"
# check was conjunctively bounded to the 7.6s created_at burst window, so
# fixture-pattern rows created OUTSIDE that window (the realistic case: the
# same TEST_DATABASE_URL mistake re-run before Owner execution) were invisible
# to every check. P2b closes exactly that gap and NOTHING else is changed:
# allowlist, delete set, SERIALIZABLE single transaction, trigger
# disable/restore model, SET CONSTRAINTS ALL IMMEDIATE, FK isolation, business
# digests, rollback path are byte-identical to the audited v1
# (sha256 9cf26d42d903b1ba71ffcef92acf34b0451f4cf370a9876777a3a2e246e391a7).
#
# One-shot cleanup of the svc-workflow integration-test fixture rows that a
# Global Reader verification run mistakenly wrote into the PRODUCTION dogfood
# database  svc_workflow_dogfood_clean  in the single burst window
# 2026-08-29 08:17:36.396306+08 .. 2026-08-29 08:17:43.997024+08.
#
# Generated by investigation SVC_WORKFLOW_DOGFOOD_TEST_FIXTURE_RESIDUE_V1
# (dsh-agent-core docs/investigations/svc-workflow-dogfood-test-fixture-residue-v1.md,
#  evidence allowlist: docs/evidence/svc-workflow-test-fixture-cleanup-v1/).
# Every row below is proven test fixture by seven independent signals
# (fixed keys/prefixes, display names, context titles, idempotency keys,
#  the 7.6s time burst, exact fixture-count algebra of tests/23 @ 9e58599,
#  and two-directional FK isolation). UNKNOWN_ROW_COUNT = 0.
#
# Allowlist: exactly 224 rows / 13 tables:
#   principals 24, domains 13, domain_role_bindings 13, global_role_bindings 8,
#   workflow_definitions 13, workflow_definition_versions 13,
#   workflow_node_definitions 26, workflow_transition_definitions 13,
#   workflow_instances 19, workflow_node_visits 19,
#   workflow_context_revisions 19, workflow_events 19,
#   workflow_command_receipts 25.
#
# Safety design:
#   * gated: root (sudo) or the service owner only; local host only;
#     database name pinned to svc_workflow_dogfood_clean
#   * single SERIALIZABLE transaction; any check failure => ROLLBACK, zero writes
#   * pre-state pinning: allowlist presence, per-row pattern proof,
#     no fixture-pattern rows outside the allowlist (P2: inside the burst
#     window; P2b: over the WHOLE DB lifetime, unbounded), two-directional FK
#     isolation re-verified INSIDE the transaction (any extra reference =>
#     abort with zero writes)
#   * P2b lifetime signature (tests/23 @ 9e58599, no time bound):
#     principals Test User/HUMAN/test@example.com + Test Agent/AGENT/NULL;
#     domains test-domain-<8hex>/'Test Domain'; DOMAIN_OWNER bindings on the
#     lifetime fixture principals+domains; GLOBAL_WORKFLOW_COORDINATOR /
#     GLOBAL_WORKFLOW_READER bindings on the lifetime fixture principals;
#     definitions global-test-<8hex>/'Global Test Def'; versions v1 PUBLISHED;
#     node graph draft/Draft/0/DRAFT/WORKFLOW_CREATOR + done/Done/1/TERMINAL;
#     transitions advance/'Advance'/ADVANCE; instances uncancelled/unarchived
#     on the lifetime fixture domains/versions/creators; receipts COMPLETED
#     with ^create-<uuid-v4>$ or one of the 6 fixed test keys; context
#     revisions v1/previous NULL with the 19-value tests/23 title set;
#     node visits 1/entered_by NULL; events INSTANCE_CREATED. All sets must
#     EXACTLY equal the 224-row allowlist; drift => zero-write abort BEFORE
#     any trigger disable / DELETE; the allowlist is NEVER auto-extended.
#   * FK-safe delete order; cyclic FKs (instance<->visit/revision,
#     node<->transition) are DEFERRABLE and both sides are deleted
#   * the COMPLETED-receipt immutability trigger is disabled and re-enabled
#     INSIDE the same transaction (PostgreSQL DDL is transactional; a
#     rollback restores it)
#   * business (non-allowlist) rows pinned by count+md5 digest per table,
#     compared pre/post => no collateral damage possible
#   * post-checks: every allowlist count == 0; digests unchanged; then COMMIT
#   * DATABASE_URL / password never printed; password only via PGPASSWORD env
#   * audit trail: full transcript to /tmp/svc-workflow-test-fixture-cleanup-v2-<ts>.log
#
# Owner execution (single command):
#   sudo bash /tmp/run-svc-workflow-test-fixture-cleanup-v2.sh
#
# Dry-run (executes the FULL path — checks, guarded deletes, post-checks —
# then ROLLBACKs instead of COMMITting; guaranteed zero committed writes):
#   SVC_WF_CLEANUP_DRYRUN=1 bash /tmp/run-svc-workflow-test-fixture-cleanup-v2.sh
#
# Recommended: run in a quiet window (the live com.svc-workflow service keeps
# open connections; SERIALIZABLE + lock_timeout='15s' makes conflicts abort
# cleanly rather than corrupt — rerun if it aborts).
#
set -euo pipefail
umask 077

ENV_FILE='/Users/yanfenma/.local/services/svc-workflow/.env'
EXPECTED_DB='svc_workflow_dogfood_clean'
DRYRUN="${SVC_WF_CLEANUP_DRYRUN:-0}"
TS=$(date +%Y%m%dT%H%M%S)
LOG="/tmp/svc-workflow-test-fixture-cleanup-v2-${TS}.log"

if [ "$(id -un)" != 'root' ] && [ "$(id -un)" != 'yanfenma' ]; then
  echo 'REFUSED: run as root (sudo) or as yanfenma' >&2; exit 1
fi
command -v psql >/dev/null 2>&1 || { echo 'REFUSED: psql not found' >&2; exit 1; }
[ -r "$ENV_FILE" ] || { echo "REFUSED: cannot read $ENV_FILE" >&2; exit 1; }

raw=$(grep -E '^DATABASE_URL=' "$ENV_FILE" | head -1 | cut -d= -f2-)
if ! printf '%s' "$raw" | grep -Eq '^postgresql://[^:]+:[^@]*@(localhost|127\.0\.0\.1|\[::1\]):[0-9]+/[A-Za-z0-9_]+$'; then
  echo 'REFUSED: DATABASE_URL does not match the pinned local dogfood DSN shape' >&2; exit 1
fi
db_user=$(printf '%s' "$raw" | sed -E 's|^postgresql://([^:]+):.*|\1|')
db_pass=$(printf '%s' "$raw" | sed -E 's|^postgresql://[^:]+:([^@]*)@.*|\1|')
db_host=$(printf '%s' "$raw" | sed -E 's|^postgresql://[^@]*@([^:/]+):.*|\1|')
db_port=$(printf '%s' "$raw" | sed -E 's|^postgresql://[^@]*@[^:]+:([0-9]+)/.*|\1|')
db_name=$(printf '%s' "$raw" | sed -E 's|.*/([A-Za-z0-9_]+)$|\1|')
if [ "$db_name" != "$EXPECTED_DB" ]; then
  echo "REFUSED: database is '$db_name', expected '$EXPECTED_DB'" >&2; exit 1
fi
export PGPASSWORD="$db_pass"
echo "svc-workflow test-fixture cleanup  ts=${TS}  dryrun=${DRYRUN}"
echo "target: $db_name @ $db_host:$db_port (user: $db_user)"
echo "transcript: $LOG"
echo

if [ "$DRYRUN" = "1" ]; then PSQL_DRY=1; else PSQL_DRY=0; fi

set +e

psql -h "$db_host" -p "$db_port" -U "$db_user" -d "$db_name" \
     -v ON_ERROR_STOP=1 -v dryrun="$PSQL_DRY" <<'SQLEOF' 2>&1 | tee "$LOG"

\set QUIET ON
\pset pager off
BEGIN ISOLATION LEVEL SERIALIZABLE;
SET LOCAL lock_timeout = '15s';
SET LOCAL statement_timeout = '120s';

DO $$ BEGIN
  IF current_database() <> 'svc_workflow_dogfood_clean' THEN
    RAISE EXCEPTION 'wrong database: %', current_database();
  END IF;
END $$;

-- ===== P0: allowlist temp tables (session-local, transaction-scoped) =====
CREATE TEMP TABLE allow_p(principal_id uuid PRIMARY KEY);
INSERT INTO allow_p VALUES
('0d165312-b1d5-4798-82cd-96e2f12300ab'),
('12724050-12a8-4c64-a5f3-93055797f5fa'),
('21380fce-3d81-47a0-b8b4-045560ef8175'),
('2416f5fa-bd4f-4650-9b85-0ffcd6a00e0d'),
('2e0baa99-bbc3-434f-80ec-02c48a6e0e7f'),
('37344ace-bcb4-4948-becf-9ae52979fca3'),
('4839e512-600a-40c4-810d-f16a9e7386c1'),
('7792815b-66cb-46f2-b255-872fc71ee5dc'),
('82b03705-adab-4b8b-8262-cb2f61aea1bb'),
('95d375c5-a93d-42ba-8a0b-eff7c8314c00'),
('9691f4be-e367-4e00-ba8a-8ba6509c837b'),
('ad395450-d9c2-4498-882c-41543e8fea0b'),
('b9e9243e-d263-48c0-912d-cf24ac3c2b69'),
('bd1a2421-2a9b-4563-97fc-536b1b57dcf0'),
('bef740f6-7b4c-4a79-b571-786874069909'),
('c24bdad3-5b38-4445-b8c0-c50d295c524d'),
('c5252e19-dbef-4dc5-8756-2b1bb711762d'),
('c70d479d-d4c7-4bae-9946-07de3712d34d'),
('ca571ede-3bbc-432e-a2eb-db32510ed852'),
('d58b5396-3e7b-411b-a4b1-7bc0ad5bf5ca'),
('e29aa560-6d2b-4e90-89b6-2f571086d4c4'),
('e2b939de-0338-43f1-9444-c6d218baa8c0'),
('e3bd7ac3-927d-4357-820d-9116c1b5c7c7'),
('ffc80044-4de4-4c7e-9cc5-de3aa4c306b0');

CREATE TEMP TABLE allow_dom(domain_id uuid PRIMARY KEY);
INSERT INTO allow_dom VALUES
('09c16593-feb5-43cd-b68b-f8fa3950601f'),
('1d1fd277-3f6d-4aa3-be78-8d1270961b4e'),
('38d2919b-7564-4716-a70a-2b45b000092f'),
('39976002-c267-4452-87dd-36a0b5fb6be8'),
('42474d42-f5f5-40a0-9217-aac4740e203c'),
('4b5f911e-ec09-45b1-8120-24e5d61b9260'),
('8ba22c39-1e3d-4afa-ae1f-178e9953abe0'),
('96ae11eb-1df3-4bdb-9c64-0bb967589280'),
('9d7a34e1-5c60-4f57-a211-80651a7393b4'),
('a9b880e3-271c-48fe-b3b6-df414a85f06e'),
('b2a48a6a-1b59-42c2-90b6-fb0beb40e6da'),
('ca2d8b53-909b-4b50-b216-75efc8985b56'),
('f01c2f86-330a-4553-a33f-12c4ad8a94e5');

CREATE TEMP TABLE allow_drb(binding_id uuid PRIMARY KEY);
INSERT INTO allow_drb VALUES
('03fea453-cea3-46f5-a766-834bc5c49d3a'),
('12df5562-0ed2-4929-891e-36577b1914f8'),
('268ecc84-8827-4671-93bd-3663930e37b2'),
('27417e68-c9fb-4441-8938-7cad0623a485'),
('41ec6bb1-321b-43ba-bc29-77c01593bcc8'),
('53ca3636-fd49-4dd3-aa42-353205124e70'),
('5ed97e80-43df-4582-ac95-e7ba43454f62'),
('75cfff84-c759-41c2-aef8-4f7582872a9d'),
('c3525be4-38f5-4b0f-be68-c28ff95c7584'),
('c7e007d6-5ca7-48e5-9f60-5ab268c626c8'),
('e7997ce3-c049-47cd-ba1a-3537208b6cf8'),
('ef6e008d-cb6d-4d9b-b8a6-c73711db1e84'),
('f2d14073-5d69-4abe-91ea-b53707b7740b');

CREATE TEMP TABLE allow_g(binding_id uuid PRIMARY KEY);
INSERT INTO allow_g VALUES
('02ced9fa-5a80-482e-b748-7ef3c2aadd62'),
('0bff8278-8f72-4700-83af-ac92447ad5d5'),
('0c4475db-adbf-460a-80ea-023a5b3bdfd5'),
('577ee7a2-c224-49c0-b83e-09f69ade8420'),
('60517727-0702-4e72-9f8d-72d900a88834'),
('69a2b5a3-064f-4184-9b5d-c9bf9cc97ff1'),
('c376231b-5280-4530-8b87-50e864bd5096'),
('cff5354c-1926-4b07-ad58-7b0185128279');

CREATE TEMP TABLE allow_def(workflow_definition_id uuid PRIMARY KEY);
INSERT INTO allow_def VALUES
('5d2aad87-1069-4cc7-91d5-b06b03b33e15'),
('6e406081-268a-42f0-832a-b3887976999c'),
('85d22e72-f7f1-4166-b5b7-79deb50ab77e'),
('a4c2ff7a-d17e-466e-a34b-c65f15afec60'),
('a5b91e45-3562-4377-b0e7-ea1ca755e8f7'),
('b4670fe4-8506-4fc7-abfe-95c5e7b1d0f9'),
('b59a37c4-9e5f-4323-b419-cd08228ed6ee'),
('bad23466-3444-41aa-89fc-c4d9b018f250'),
('bfdc90d0-0c26-4502-b7e4-163aadc03596'),
('c778728f-f2fa-469c-9d39-eb48c4f55944'),
('e1a8c197-c0ed-4750-adc9-44268c20fb68'),
('fc2cb98d-69bb-4172-a69e-0ac33114c73c'),
('fe758916-6997-474b-92ce-fee1b0423015');

CREATE TEMP TABLE allow_ver(definition_version_id uuid PRIMARY KEY);
INSERT INTO allow_ver VALUES
('1e0c5863-23ef-4328-8224-18a6957a9867'),
('22b8d384-267c-4469-b431-59795c834dd2'),
('362a2185-e9e8-4ada-a69e-3cf2e43b5f9c'),
('36c3b015-3578-483b-8c12-40a2186a0527'),
('54fe4ed4-7431-4e8f-bfc8-bb0f6a6f3f3f'),
('7396ac7a-b166-40f2-9f92-48e5ca887638'),
('85fd994d-f35a-4b0d-8504-7476a8f6e714'),
('940a085e-1a3f-4a83-9703-70608f0d2289'),
('a2bf5360-c3f8-4b77-833b-9439f5a4d1dc'),
('b9d81fa7-d999-4598-8db9-920a64bb866f'),
('d3ae2f95-7fcb-438a-929e-28a67c7ac63e'),
('d4c04e56-4d4e-43e2-bd32-392b59554176'),
('ea14d175-a086-4427-8ba7-fe93c9e31ed2');

CREATE TEMP TABLE allow_n(node_id uuid PRIMARY KEY);
INSERT INTO allow_n VALUES
('0af5d7f6-c40b-418f-bad1-fdb308d76006'),
('12b77177-1ae5-4a11-9587-085953669125'),
('34e0c08b-3c56-4593-b3b2-3525dd56847b'),
('39f28ae5-8256-4701-95c7-8bafcdb2e93d'),
('49fce116-83cb-4df8-89c5-7a7bcebc693f'),
('522d2575-01ba-48c6-afd9-2d2d5e4f36b2'),
('59f87a78-9b72-4e4b-b8b6-35f69506b076'),
('610c70b3-b4cd-4e94-b841-9a2b78733505'),
('66da20bc-65f8-4939-afe3-be6a6efb143c'),
('6a9341b0-675d-4630-9009-da000c011b50'),
('811c2c79-2f19-43e4-b7c1-922a723a8c29'),
('8257b009-f413-4f08-85af-6ca87a60c5ea'),
('83dff530-f08d-411e-825f-fe08860f7afd'),
('887843fe-d810-4353-9d83-79a58b79227d'),
('8e3de483-614a-46a4-99b3-cef4f8b61036'),
('a92ddb33-5f25-4207-85c1-894f45d8b983'),
('afb2d6a7-56b2-424c-8a05-1ab8078898bd'),
('c37c2153-b4b3-4819-a9fd-5878747e546e'),
('cb127c6c-8816-44f8-a5c4-fb3f8ada383b'),
('cb4f0991-329a-48a8-a947-bea07fbfdee0'),
('d9edea54-90c2-4106-b8f0-dd8737f82926'),
('dab87fe8-d877-49b5-b0ff-3f2d1cc2d761'),
('dcdbdbb0-d5e6-4325-85eb-f3422aa42a46'),
('dd545ff8-7278-406b-86ae-a5edf288ef04'),
('f2f6f77c-2abc-423b-aad0-5944099a7a0d'),
('fda231e3-35f2-4008-bdf1-5820da561b8a');

CREATE TEMP TABLE allow_t(transition_id uuid PRIMARY KEY);
INSERT INTO allow_t VALUES
('0f79f43b-7e5d-4761-956d-4bc46eac3705'),
('124d09c9-3a6b-40ec-8588-e475f1c3f20b'),
('2ef05d77-22b4-4f1c-a577-6e6fba2af40b'),
('3706b7ae-7f41-459b-afea-1d81a92fb953'),
('5d1e6b1e-1b99-4043-ac3a-a260cc0bb1b5'),
('843aaecd-198d-491a-9b18-2162f836b91b'),
('bba2c5c8-7107-4492-9880-35613a0fffd4'),
('bc4d6529-9e7a-4a87-805c-07693d2bfda8'),
('c2a542c7-80da-4a4e-9de8-d10f69c2ecbd'),
('c358ce2b-42e1-4e65-bd37-370dd8e0685f'),
('d0c634b7-b49d-4e76-8035-01327e5a792c'),
('d23ad190-29ec-4755-af9c-b1ea68b593c3'),
('dd131ce9-9375-467e-87d4-0e7ad3ae73c4');

CREATE TEMP TABLE allow_i(workflow_instance_id uuid PRIMARY KEY);
INSERT INTO allow_i VALUES
('0da857fb-e2fb-4d94-8b80-e749db28b5bb'),
('292ad1f2-3ae2-4150-9a45-86981f2e04a7'),
('4adc82e2-d06c-41ab-a147-48b3756a5bae'),
('508bd330-5a26-4201-aeb6-6d547a96b5e5'),
('5e5b6d30-22ac-4539-bbd4-0a8b4e3dabb3'),
('67ea5229-8b54-424c-84f1-5fd5607375d1'),
('6c648a0c-adc6-45c2-8ef1-09459f092f36'),
('6ed185e2-8a87-4181-841c-16a344a216a2'),
('73757057-0c5d-4768-968b-74b3563ccccf'),
('9cd6f651-24bd-48c3-902e-8e6188fc6f32'),
('a9ee105b-4932-4fc9-bf7e-46a8db5eef4c'),
('c3c4fe13-e7eb-4018-bbe4-c8945bb2aece'),
('c751782e-157c-49e8-80c3-e86d207c8896'),
('cc398199-0591-47c2-a3a6-7f29fd33c594'),
('d7ed541c-1802-466f-b132-c1f5bfea7d2a'),
('d9913dac-6c08-48ac-bb5a-aa33c9cc0c34'),
('dd812209-afd7-4ea8-bcca-18271a5bc497'),
('f18d704a-8711-4bd4-89ff-9c10dc93316a'),
('fc272b85-e003-4f34-8fce-084cc4474d70');

CREATE TEMP TABLE allow_v(node_visit_id uuid PRIMARY KEY);
INSERT INTO allow_v VALUES
('0826c4ed-2c2f-4277-adca-ba944e3ac7f4'),
('0f4e1880-df11-4656-a4c0-584ec41047f8'),
('16ed7dc5-c823-4e0b-8027-4de4c2c52d65'),
('24245304-2db9-47ff-9565-4cd3dd7e0ac4'),
('4c3f143a-9604-42ce-9889-32c0af407406'),
('7ccd1993-4248-4a2f-bf32-bf63077e5f13'),
('7e2093eb-d26c-4f51-ae82-166d1c999482'),
('83325f65-d762-4fe6-86bd-73b6982332a2'),
('92bf0f4c-c3a0-4886-9380-68967a3438a1'),
('a0552355-63dc-4a20-b1ec-13f8eb35fe93'),
('a43011d7-4dc4-4fd3-8cc1-11fdcbe8f9b2'),
('c6641274-b4e7-4635-811a-c1ce7a6810d7'),
('c8857a13-f325-4b50-ad54-932b24fbdf4d'),
('d6196b05-1ff1-42b1-acb3-1967e02e8de3'),
('d74375b1-6827-4e53-acc8-4e5937b53698'),
('dab7a91b-b94c-442f-b2ed-29faf4d93f44'),
('ea05edba-fb37-45c9-a58e-022aed90f45b'),
('ed736fd8-67c8-406d-aa6e-1a2b8b42f1a2'),
('f94234b0-f4fe-4525-aca5-a5f323408438');

CREATE TEMP TABLE allow_r(context_revision_id uuid PRIMARY KEY);
INSERT INTO allow_r VALUES
('214bf1cf-1baa-45f1-b29a-cfd185b04708'),
('29264522-cc28-4619-a364-6f52e910b8e9'),
('4eaceb23-77ee-4c04-9a5f-b764404604d9'),
('50a39ba8-0d0f-4c6f-b0b4-6a4939dadaaf'),
('5b0b3b09-04ea-419f-a66b-8b595826ac6e'),
('67a4e2ca-df44-4525-9332-9450b3767213'),
('750cde8f-6ecc-4600-8e43-e7a5c63a3b41'),
('758f2a5e-c189-4411-9a09-ee075cc77c45'),
('7d809ef4-ae79-4712-bf31-99eded671764'),
('90e816ef-fa7a-4399-9cc4-14b668d82a08'),
('93f18403-fd3f-4b26-9302-902dcbf38cd7'),
('963cc4f1-2cd5-4042-b3b9-341fe9cdf1da'),
('a6474db7-5ee2-4a88-9ca6-3ad505696e2a'),
('a665001a-470d-4e1a-97dc-8b2105912ccb'),
('b0093436-0e89-4841-9087-f4e427de550b'),
('bfc377d3-a3d1-45db-971b-f93ed5968cce'),
('d5317d07-582d-4e4e-8068-ca2a4d6e83f4'),
('d9f3e43a-9efd-45e4-b09d-31b50dc9a9b0'),
('ec79b28b-af90-47cb-85dc-505d3636b412');

CREATE TEMP TABLE allow_e(event_id uuid PRIMARY KEY);
INSERT INTO allow_e VALUES
('056c1e10-b939-479a-8e2f-8dbdeefe1a75'),
('26f494d5-fee2-4ebe-bbef-c38d31509885'),
('272990ca-b7f1-4cd5-b810-78b3a4b525ed'),
('2b48eccc-b648-4cd9-bf71-4786c5cd2fec'),
('50df2f57-7718-4819-8676-5b1be4a59845'),
('566bf9ad-d016-47b5-971f-6032c7cfd90a'),
('71fd6e64-d81b-45d2-b06c-cb6258121cb0'),
('7619241d-6316-4512-a3bb-660de1f7ded3'),
('7853ce4d-6264-4978-b464-2298d1229fad'),
('80cdde98-5992-4d5f-bbaf-509b6cf8ff93'),
('9674b2ec-c4f4-4e90-9806-d9f3e1393fe8'),
('9d3ea94a-c507-4ea3-80e2-af031f9a1ddf'),
('bca454f1-3a1b-4595-b4cc-67f4edc5510d'),
('c59d74dd-8cc6-49b7-9520-f3bf8998229a'),
('cad834da-5cb7-4efb-9127-4354f8417430'),
('e9b4e148-5e82-4380-9d76-adeea52685ff'),
('f7aa34ab-daf4-4150-8cab-12cc1c2c4863'),
('f843cb32-9dbf-40e1-a9a1-f1f3675371b4'),
('fd6a4f04-7aa1-4bb0-9369-0f33bb68c7d5');

CREATE TEMP TABLE allow_c(command_id uuid PRIMARY KEY);
INSERT INTO allow_c VALUES
('0bc95d31-dca8-4a71-bbb5-2c61334ba848'),
('156d0713-97b6-4b3f-8e7c-955b5acdc41c'),
('1fe6a96a-ebdb-42bb-9d54-72f609d8ca46'),
('25249e93-21a7-4c00-94f3-cbd332ea2dad'),
('27f1b1f0-4cad-45f9-a407-bfe6eab52aa7'),
('2aff9e4b-6e17-4466-aa87-e979e52cee25'),
('2fe5c85e-452f-462f-af90-5008e7f40012'),
('3b6dded6-d5e0-440d-9d14-af6ecbd415f5'),
('474d63b7-5136-4b15-8b90-e8a03714daac'),
('4f2b9c0c-ac03-44d6-92a8-5adc6d645ce8'),
('78e97bb6-6c90-4786-8686-6db179a3fe63'),
('87688a81-7911-49e6-86fc-19f0be033f47'),
('957d9d84-f735-4654-8471-59a0da8d33c7'),
('9924292a-5fcc-45f5-bcc7-9f5387077879'),
('a066d1c3-5f7e-46e3-85c1-bf55c5ef09f6'),
('b172257a-8898-40ce-b69f-80c828d21f1f'),
('b1f05f5a-e5a2-4575-b73d-ca269a0294c1'),
('b8a3aebb-83a3-4ac3-a360-4b675c57cb3f'),
('bb9f2974-0635-4c4d-a43d-aeb6d1ca2240'),
('d45df76f-0a03-4e89-ace9-8583673eff25'),
('dbc87a56-14f0-4c3d-a4bc-84cfa31132a7'),
('de696711-7109-4fe2-ad7b-3b436fbec0fb'),
('e102b54a-fb2f-4ebf-a83b-423c14be1895'),
('effd58a5-618b-4d84-b67d-8430039c0cf2'),
('f98df7ff-44a2-429d-9985-df95690af7ed');

-- ===== P1/P2/P3: presence + pattern proof + no unlisted fixture rows =====
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM principals x WHERE x.principal_id IN (SELECT principal_id FROM allow_p)' INTO inlist;
  IF inlist <> 24 THEN RAISE EXCEPTION 'P1 principals: allowlist present=% expected=24', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM principals x WHERE x.principal_id NOT IN (SELECT principal_id FROM allow_p) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.display_name IN ('Test User','Test Agent') AND ((x.principal_type='HUMAN' AND x.email='test@example.com') OR (x.principal_type='AGENT' AND x.email IS NULL))$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 principals: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM principals x WHERE x.principal_id IN (SELECT principal_id FROM allow_p) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.display_name IN ('Test User','Test Agent') AND ((x.principal_type='HUMAN' AND x.email='test@example.com') OR (x.principal_type='AGENT' AND x.email IS NULL))$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 principals: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM domains x WHERE x.domain_id IN (SELECT domain_id FROM allow_dom)' INTO inlist;
  IF inlist <> 13 THEN RAISE EXCEPTION 'P1 domains: allowlist present=% expected=13', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM domains x WHERE x.domain_id NOT IN (SELECT domain_id FROM allow_dom) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.domain_key LIKE 'test-domain-%' AND x.display_name='Test Domain'$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 domains: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM domains x WHERE x.domain_id IN (SELECT domain_id FROM allow_dom) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.domain_key LIKE 'test-domain-%' AND x.display_name='Test Domain'$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 domains: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM domain_role_bindings x WHERE x.binding_id IN (SELECT binding_id FROM allow_drb)' INTO inlist;
  IF inlist <> 13 THEN RAISE EXCEPTION 'P1 domain_role_bindings: allowlist present=% expected=13', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM domain_role_bindings x WHERE x.binding_id NOT IN (SELECT binding_id FROM allow_drb) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.role_key='DOMAIN_OWNER' AND x.enabled AND x.domain_id IN (SELECT domain_id FROM allow_dom) AND x.principal_id IN (SELECT principal_id FROM allow_p)$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 domain_role_bindings: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM domain_role_bindings x WHERE x.binding_id IN (SELECT binding_id FROM allow_drb) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.role_key='DOMAIN_OWNER' AND x.enabled AND x.domain_id IN (SELECT domain_id FROM allow_dom) AND x.principal_id IN (SELECT principal_id FROM allow_p)$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 domain_role_bindings: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM global_role_bindings x WHERE x.binding_id IN (SELECT binding_id FROM allow_g)' INTO inlist;
  IF inlist <> 8 THEN RAISE EXCEPTION 'P1 global_role_bindings: allowlist present=% expected=8', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM global_role_bindings x WHERE x.binding_id NOT IN (SELECT binding_id FROM allow_g) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.role_key IN ('GLOBAL_WORKFLOW_COORDINATOR','GLOBAL_WORKFLOW_READER') AND x.principal_id IN (SELECT principal_id FROM allow_p)$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 global_role_bindings: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM global_role_bindings x WHERE x.binding_id IN (SELECT binding_id FROM allow_g) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.role_key IN ('GLOBAL_WORKFLOW_COORDINATOR','GLOBAL_WORKFLOW_READER') AND x.principal_id IN (SELECT principal_id FROM allow_p)$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 global_role_bindings: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_definitions x WHERE x.workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def)' INTO inlist;
  IF inlist <> 13 THEN RAISE EXCEPTION 'P1 workflow_definitions: allowlist present=% expected=13', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_definitions x WHERE x.workflow_definition_id NOT IN (SELECT workflow_definition_id FROM allow_def) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.definition_key LIKE 'global-test-%' AND x.display_name='Global Test Def' AND x.domain_id IN (SELECT domain_id FROM allow_dom)$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_definitions: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_definitions x WHERE x.workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.definition_key LIKE 'global-test-%' AND x.display_name='Global Test Def' AND x.domain_id IN (SELECT domain_id FROM allow_dom)$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_definitions: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_definition_versions x WHERE x.definition_version_id IN (SELECT definition_version_id FROM allow_ver)' INTO inlist;
  IF inlist <> 13 THEN RAISE EXCEPTION 'P1 workflow_definition_versions: allowlist present=% expected=13', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_definition_versions x WHERE x.definition_version_id NOT IN (SELECT definition_version_id FROM allow_ver) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def) AND x.version_number=1 AND x.version_status='PUBLISHED'$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_definition_versions: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_definition_versions x WHERE x.definition_version_id IN (SELECT definition_version_id FROM allow_ver) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def) AND x.version_number=1 AND x.version_status='PUBLISHED'$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_definition_versions: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_node_definitions x WHERE x.node_id IN (SELECT node_id FROM allow_n)' INTO inlist;
  IF inlist <> 26 THEN RAISE EXCEPTION 'P1 workflow_node_definitions: allowlist present=% expected=26', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_node_definitions x WHERE x.node_id NOT IN (SELECT node_id FROM allow_n) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.definition_version_id IN (SELECT definition_version_id FROM allow_ver) AND x.node_key IN ('draft','done') AND x.fixed_principal_id IS NULL$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_node_definitions: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_node_definitions x WHERE x.node_id IN (SELECT node_id FROM allow_n) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.definition_version_id IN (SELECT definition_version_id FROM allow_ver) AND x.node_key IN ('draft','done') AND x.fixed_principal_id IS NULL$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_node_definitions: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_transition_definitions x WHERE x.transition_id IN (SELECT transition_id FROM allow_t)' INTO inlist;
  IF inlist <> 13 THEN RAISE EXCEPTION 'P1 workflow_transition_definitions: allowlist present=% expected=13', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_transition_definitions x WHERE x.transition_id NOT IN (SELECT transition_id FROM allow_t) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.definition_version_id IN (SELECT definition_version_id FROM allow_ver) AND x.transition_key='advance' AND x.transition_effect='ADVANCE'$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_transition_definitions: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_transition_definitions x WHERE x.transition_id IN (SELECT transition_id FROM allow_t) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.definition_version_id IN (SELECT definition_version_id FROM allow_ver) AND x.transition_key='advance' AND x.transition_effect='ADVANCE'$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_transition_definitions: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_instances x WHERE x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i)' INTO inlist;
  IF inlist <> 19 THEN RAISE EXCEPTION 'P1 workflow_instances: allowlist present=% expected=19', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_instances x WHERE x.workflow_instance_id NOT IN (SELECT workflow_instance_id FROM allow_i) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.domain_id IN (SELECT domain_id FROM allow_dom) AND x.definition_version_id IN (SELECT definition_version_id FROM allow_ver) AND x.created_by_principal_id IN (SELECT principal_id FROM allow_p) AND x.cancelled=false AND x.archived_at IS NULL AND x.cancelled_by_principal_id IS NULL AND x.archived_by_principal_id IS NULL$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_instances: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_instances x WHERE x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.domain_id IN (SELECT domain_id FROM allow_dom) AND x.definition_version_id IN (SELECT definition_version_id FROM allow_ver) AND x.created_by_principal_id IN (SELECT principal_id FROM allow_p) AND x.cancelled=false AND x.archived_at IS NULL AND x.cancelled_by_principal_id IS NULL AND x.archived_by_principal_id IS NULL$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_instances: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_node_visits x WHERE x.node_visit_id IN (SELECT node_visit_id FROM allow_v)' INTO inlist;
  IF inlist <> 19 THEN RAISE EXCEPTION 'P1 workflow_node_visits: allowlist present=% expected=19', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_node_visits x WHERE x.node_visit_id NOT IN (SELECT node_visit_id FROM allow_v) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) AND x.visit_number=1 AND x.assignee_principal_id IN (SELECT principal_id FROM allow_p) AND x.entered_by_transition_id IS NULL$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_node_visits: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_node_visits x WHERE x.node_visit_id IN (SELECT node_visit_id FROM allow_v) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) AND x.visit_number=1 AND x.assignee_principal_id IN (SELECT principal_id FROM allow_p) AND x.entered_by_transition_id IS NULL$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_node_visits: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_context_revisions x WHERE x.context_revision_id IN (SELECT context_revision_id FROM allow_r)' INTO inlist;
  IF inlist <> 19 THEN RAISE EXCEPTION 'P1 workflow_context_revisions: allowlist present=% expected=19', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_context_revisions x WHERE x.context_revision_id NOT IN (SELECT context_revision_id FROM allow_r) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) AND x.revision_number=1 AND x.created_by_principal_id IN (SELECT principal_id FROM allow_p) AND x.previous_revision_id IS NULL$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_context_revisions: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_context_revisions x WHERE x.context_revision_id IN (SELECT context_revision_id FROM allow_r) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) AND x.revision_number=1 AND x.created_by_principal_id IN (SELECT principal_id FROM allow_p) AND x.previous_revision_id IS NULL$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_context_revisions: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_events x WHERE x.event_id IN (SELECT event_id FROM allow_e)' INTO inlist;
  IF inlist <> 19 THEN RAISE EXCEPTION 'P1 workflow_events: allowlist present=% expected=19', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_events x WHERE x.event_id NOT IN (SELECT event_id FROM allow_e) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.event_type='INSTANCE_CREATED' AND x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) AND x.command_id IN (SELECT command_id FROM allow_c) AND x.actor_principal_id IN (SELECT principal_id FROM allow_p)$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_events: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_events x WHERE x.event_id IN (SELECT event_id FROM allow_e) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.event_type='INSTANCE_CREATED' AND x.workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) AND x.command_id IN (SELECT command_id FROM allow_c) AND x.actor_principal_id IN (SELECT principal_id FROM allow_p)$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_events: % allowlist rows fail pattern proof', badpat; END IF;
END $$;
DO $$
DECLARE inlist int; extra int; badpat int;
BEGIN
  EXECUTE 'SELECT count(*) FROM workflow_command_receipts x WHERE x.command_id IN (SELECT command_id FROM allow_c)' INTO inlist;
  IF inlist <> 25 THEN RAISE EXCEPTION 'P1 workflow_command_receipts: allowlist present=% expected=25', inlist; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_command_receipts x WHERE x.command_id NOT IN (SELECT command_id FROM allow_c) AND ' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.receipt_status='COMPLETED' AND (x.idempotency_key ~ '^create-[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$' OR x.idempotency_key IN ('grant-global-1','revoke-global-1','transition-coord-1','grant-reader-1','revoke-reader-1','reader-denied-transition-1')) AND x.principal_id IN (SELECT principal_id FROM allow_p)$PAT$ INTO extra;
  IF extra <> 0 THEN RAISE EXCEPTION 'P2 workflow_command_receipts: % fixture-pattern rows OUTSIDE allowlist — drift detected, aborting', extra; END IF;
  EXECUTE 'SELECT count(*) FROM workflow_command_receipts x WHERE x.command_id IN (SELECT command_id FROM allow_c) AND NOT (' || $PAT$x.created_at >= '2026-08-29 08:17:36+08'::timestamptz AND x.created_at < '2026-08-29 08:17:45+08'::timestamptz AND x.receipt_status='COMPLETED' AND (x.idempotency_key ~ '^create-[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$' OR x.idempotency_key IN ('grant-global-1','revoke-global-1','transition-coord-1','grant-reader-1','revoke-reader-1','reader-denied-transition-1')) AND x.principal_id IN (SELECT principal_id FROM allow_p)$PAT$ || ')' INTO badpat;
  IF badpat <> 0 THEN RAISE EXCEPTION 'P3 workflow_command_receipts: % allowlist rows fail pattern proof', badpat; END IF;
END $$;

-- ===== P2b: LIFETIME_FIXTURE_PATTERN_DRIFT_GATE (v2 revision, audit B1) =====
-- Unbounded (NO created_at window) recomputation, per table, of the set of
-- rows mechanically matching the tests/23_global_coordinator.rs @ 9e58599
-- fixture signature. Lifetime sets cross-reference EACH OTHER (never the
-- allow_* tables), so a second SELF-CONTAINED fixture island (the realistic
-- drift: the same TEST_DATABASE_URL mistake re-run after the burst window)
-- is fully visible. ALL_LIFETIME_MATCHING_ROW_IDS must EXACTLY equal the
-- 224-row allowlist: EXTRA (pattern row outside the allowlist) or MISSING
-- (allowlist row no longer matching) => abort with ZERO writes, BEFORE any
-- trigger disable and BEFORE any DELETE. The allowlist is NEVER auto-extended;
-- drift is escalated to a human via a new investigation round.
CREATE TEMP TABLE lf_p AS SELECT principal_id FROM principals WHERE display_name IN ('Test User','Test Agent') AND ((principal_type='HUMAN' AND email='test@example.com') OR (principal_type='AGENT' AND email IS NULL)) AND enabled;
CREATE TEMP TABLE lf_dom AS SELECT domain_id FROM domains WHERE domain_key ~ '^test-domain-[0-9a-f]{8}$' AND display_name='Test Domain' AND enabled;
CREATE TEMP TABLE lf_drb AS SELECT b.binding_id FROM domain_role_bindings b WHERE b.role_key='DOMAIN_OWNER' AND b.enabled AND b.domain_id IN (SELECT domain_id FROM lf_dom) AND b.principal_id IN (SELECT principal_id FROM lf_p);
CREATE TEMP TABLE lf_g AS SELECT b.binding_id FROM global_role_bindings b WHERE b.role_key IN ('GLOBAL_WORKFLOW_COORDINATOR','GLOBAL_WORKFLOW_READER') AND b.principal_id IN (SELECT principal_id FROM lf_p);
CREATE TEMP TABLE lf_def AS SELECT d.workflow_definition_id FROM workflow_definitions d WHERE d.definition_key ~ '^global-test-[0-9a-f]{8}$' AND d.display_name='Global Test Def' AND d.domain_id IN (SELECT domain_id FROM lf_dom);
CREATE TEMP TABLE lf_ver AS SELECT v.definition_version_id FROM workflow_definition_versions v WHERE v.version_number=1 AND v.version_status='PUBLISHED' AND v.context_schema IS NULL AND v.workflow_definition_id IN (SELECT workflow_definition_id FROM lf_def);
CREATE TEMP TABLE lf_n AS SELECT n.node_id FROM workflow_node_definitions n WHERE n.definition_version_id IN (SELECT definition_version_id FROM lf_ver) AND ((n.node_key='draft' AND n.display_name='Draft' AND n.order_index=0 AND n.node_type='DRAFT' AND n.assignee_ref_type='WORKFLOW_CREATOR') OR (n.node_key='done' AND n.display_name='Done' AND n.order_index=1 AND n.node_type='TERMINAL' AND n.assignee_ref_type IS NULL)) AND n.fixed_principal_id IS NULL;
CREATE TEMP TABLE lf_t AS SELECT t.transition_id FROM workflow_transition_definitions t WHERE t.transition_key='advance' AND t.display_name='Advance' AND t.transition_effect='ADVANCE' AND t.definition_version_id IN (SELECT definition_version_id FROM lf_ver) AND t.source_node_id IN (SELECT node_id FROM lf_n) AND t.target_node_id IN (SELECT node_id FROM lf_n);
CREATE TEMP TABLE lf_i AS SELECT i.workflow_instance_id FROM workflow_instances i WHERE i.domain_id IN (SELECT domain_id FROM lf_dom) AND i.definition_version_id IN (SELECT definition_version_id FROM lf_ver) AND i.created_by_principal_id IN (SELECT principal_id FROM lf_p) AND i.cancelled=false AND i.archived_at IS NULL AND i.cancelled_by_principal_id IS NULL AND i.archived_by_principal_id IS NULL;
CREATE TEMP TABLE lf_c AS SELECT c.command_id FROM workflow_command_receipts c WHERE c.receipt_status='COMPLETED' AND (c.idempotency_key ~ '^create-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' OR c.idempotency_key IN ('grant-global-1','revoke-global-1','transition-coord-1','grant-reader-1','revoke-reader-1','reader-denied-transition-1')) AND c.principal_id IN (SELECT principal_id FROM lf_p);
CREATE TEMP TABLE lf_r AS SELECT r.context_revision_id FROM workflow_context_revisions r WHERE r.revision_number=1 AND r.previous_revision_id IS NULL AND r.created_by_principal_id IN (SELECT principal_id FROM lf_p) AND r.workflow_instance_id IN (SELECT workflow_instance_id FROM lf_i) AND r.payload->>'title' IN ('alpha-1','alpha-2','beta-1','page-0','page-1','page-2','page-3','page-4','summary-1','denied-1','boundary-a','boundary-b','lifecycle-1','reader-a1','reader-a2','reader-b1','reader-write-a','reader-write-b','reader-lifecycle-1');
CREATE TEMP TABLE lf_v AS SELECT v.node_visit_id FROM workflow_node_visits v WHERE v.visit_number=1 AND v.entered_by_transition_id IS NULL AND v.workflow_instance_id IN (SELECT workflow_instance_id FROM lf_i) AND v.assignee_principal_id IN (SELECT principal_id FROM lf_p) AND v.node_id IN (SELECT node_id FROM lf_n);
CREATE TEMP TABLE lf_e AS SELECT e.event_id FROM workflow_events e WHERE e.event_type='INSTANCE_CREATED' AND e.workflow_instance_id IN (SELECT workflow_instance_id FROM lf_i) AND e.command_id IN (SELECT command_id FROM lf_c) AND e.actor_principal_id IN (SELECT principal_id FROM lf_p);

CREATE TEMP TABLE p2b_rep(t text, lf_cnt bigint, al_cnt bigint, extra bigint, missing bigint);
INSERT INTO p2b_rep SELECT 'principals', (SELECT count(*) FROM lf_p), (SELECT count(*) FROM allow_p), (SELECT count(*) FROM lf_p WHERE principal_id NOT IN (SELECT principal_id FROM allow_p)), (SELECT count(*) FROM allow_p WHERE principal_id NOT IN (SELECT principal_id FROM lf_p));
INSERT INTO p2b_rep SELECT 'domains', (SELECT count(*) FROM lf_dom), (SELECT count(*) FROM allow_dom), (SELECT count(*) FROM lf_dom WHERE domain_id NOT IN (SELECT domain_id FROM allow_dom)), (SELECT count(*) FROM allow_dom WHERE domain_id NOT IN (SELECT domain_id FROM lf_dom));
INSERT INTO p2b_rep SELECT 'domain_role_bindings', (SELECT count(*) FROM lf_drb), (SELECT count(*) FROM allow_drb), (SELECT count(*) FROM lf_drb WHERE binding_id NOT IN (SELECT binding_id FROM allow_drb)), (SELECT count(*) FROM allow_drb WHERE binding_id NOT IN (SELECT binding_id FROM lf_drb));
INSERT INTO p2b_rep SELECT 'global_role_bindings', (SELECT count(*) FROM lf_g), (SELECT count(*) FROM allow_g), (SELECT count(*) FROM lf_g WHERE binding_id NOT IN (SELECT binding_id FROM allow_g)), (SELECT count(*) FROM allow_g WHERE binding_id NOT IN (SELECT binding_id FROM lf_g));
INSERT INTO p2b_rep SELECT 'workflow_definitions', (SELECT count(*) FROM lf_def), (SELECT count(*) FROM allow_def), (SELECT count(*) FROM lf_def WHERE workflow_definition_id NOT IN (SELECT workflow_definition_id FROM allow_def)), (SELECT count(*) FROM allow_def WHERE workflow_definition_id NOT IN (SELECT workflow_definition_id FROM lf_def));
INSERT INTO p2b_rep SELECT 'workflow_definition_versions', (SELECT count(*) FROM lf_ver), (SELECT count(*) FROM allow_ver), (SELECT count(*) FROM lf_ver WHERE definition_version_id NOT IN (SELECT definition_version_id FROM allow_ver)), (SELECT count(*) FROM allow_ver WHERE definition_version_id NOT IN (SELECT definition_version_id FROM lf_ver));
INSERT INTO p2b_rep SELECT 'workflow_node_definitions', (SELECT count(*) FROM lf_n), (SELECT count(*) FROM allow_n), (SELECT count(*) FROM lf_n WHERE node_id NOT IN (SELECT node_id FROM allow_n)), (SELECT count(*) FROM allow_n WHERE node_id NOT IN (SELECT node_id FROM lf_n));
INSERT INTO p2b_rep SELECT 'workflow_transition_definitions', (SELECT count(*) FROM lf_t), (SELECT count(*) FROM allow_t), (SELECT count(*) FROM lf_t WHERE transition_id NOT IN (SELECT transition_id FROM allow_t)), (SELECT count(*) FROM allow_t WHERE transition_id NOT IN (SELECT transition_id FROM lf_t));
INSERT INTO p2b_rep SELECT 'workflow_instances', (SELECT count(*) FROM lf_i), (SELECT count(*) FROM allow_i), (SELECT count(*) FROM lf_i WHERE workflow_instance_id NOT IN (SELECT workflow_instance_id FROM allow_i)), (SELECT count(*) FROM allow_i WHERE workflow_instance_id NOT IN (SELECT workflow_instance_id FROM lf_i));
INSERT INTO p2b_rep SELECT 'workflow_command_receipts', (SELECT count(*) FROM lf_c), (SELECT count(*) FROM allow_c), (SELECT count(*) FROM lf_c WHERE command_id NOT IN (SELECT command_id FROM allow_c)), (SELECT count(*) FROM allow_c WHERE command_id NOT IN (SELECT command_id FROM lf_c));
INSERT INTO p2b_rep SELECT 'workflow_context_revisions', (SELECT count(*) FROM lf_r), (SELECT count(*) FROM allow_r), (SELECT count(*) FROM lf_r WHERE context_revision_id NOT IN (SELECT context_revision_id FROM allow_r)), (SELECT count(*) FROM allow_r WHERE context_revision_id NOT IN (SELECT context_revision_id FROM lf_r));
INSERT INTO p2b_rep SELECT 'workflow_node_visits', (SELECT count(*) FROM lf_v), (SELECT count(*) FROM allow_v), (SELECT count(*) FROM lf_v WHERE node_visit_id NOT IN (SELECT node_visit_id FROM allow_v)), (SELECT count(*) FROM allow_v WHERE node_visit_id NOT IN (SELECT node_visit_id FROM lf_v));
INSERT INTO p2b_rep SELECT 'workflow_events', (SELECT count(*) FROM lf_e), (SELECT count(*) FROM allow_e), (SELECT count(*) FROM lf_e WHERE event_id NOT IN (SELECT event_id FROM allow_e)), (SELECT count(*) FROM allow_e WHERE event_id NOT IN (SELECT event_id FROM lf_e));

\echo 'P2b LIFETIME_FIXTURE_PATTERN_DRIFT_GATE: per-table lifetime-vs-allowlist (must be equal; extra=0 missing=0):'
SELECT t, lf_cnt, al_cnt, extra, missing FROM p2b_rep ORDER BY t;
SELECT 'TOTAL' AS t, sum(lf_cnt) AS lf_cnt, sum(al_cnt) AS al_cnt, sum(extra) AS extra, sum(missing) AS missing FROM p2b_rep;
\echo 'P2b diagnostic: lifetime fixture-pattern rows OUTSIDE the allowlist (first 50; empty => none):'
SELECT 'principals' tbl, principal_id::text id FROM lf_p WHERE principal_id NOT IN (SELECT principal_id FROM allow_p)
UNION ALL SELECT 'domains', domain_id::text FROM lf_dom WHERE domain_id NOT IN (SELECT domain_id FROM allow_dom)
UNION ALL SELECT 'domain_role_bindings', binding_id::text FROM lf_drb WHERE binding_id NOT IN (SELECT binding_id FROM allow_drb)
UNION ALL SELECT 'global_role_bindings', binding_id::text FROM lf_g WHERE binding_id NOT IN (SELECT binding_id FROM allow_g)
UNION ALL SELECT 'workflow_definitions', workflow_definition_id::text FROM lf_def WHERE workflow_definition_id NOT IN (SELECT workflow_definition_id FROM allow_def)
UNION ALL SELECT 'workflow_definition_versions', definition_version_id::text FROM lf_ver WHERE definition_version_id NOT IN (SELECT definition_version_id FROM allow_ver)
UNION ALL SELECT 'workflow_node_definitions', node_id::text FROM lf_n WHERE node_id NOT IN (SELECT node_id FROM allow_n)
UNION ALL SELECT 'workflow_transition_definitions', transition_id::text FROM lf_t WHERE transition_id NOT IN (SELECT transition_id FROM allow_t)
UNION ALL SELECT 'workflow_instances', workflow_instance_id::text FROM lf_i WHERE workflow_instance_id NOT IN (SELECT workflow_instance_id FROM allow_i)
UNION ALL SELECT 'workflow_command_receipts', command_id::text FROM lf_c WHERE command_id NOT IN (SELECT command_id FROM allow_c)
UNION ALL SELECT 'workflow_context_revisions', context_revision_id::text FROM lf_r WHERE context_revision_id NOT IN (SELECT context_revision_id FROM allow_r)
UNION ALL SELECT 'workflow_node_visits', node_visit_id::text FROM lf_v WHERE node_visit_id NOT IN (SELECT node_visit_id FROM allow_v)
UNION ALL SELECT 'workflow_events', event_id::text FROM lf_e WHERE event_id NOT IN (SELECT event_id FROM allow_e)
LIMIT 50;
DO $$
DECLARE te bigint; tm bigint; bad int; det text;
BEGIN
  SELECT coalesce(sum(extra),0), coalesce(sum(missing),0), count(*) FILTER (WHERE lf_cnt <> al_cnt OR extra <> 0 OR missing <> 0),
         coalesce(string_agg(t || ' (lifetime=' || lf_cnt || ' allowlist=' || al_cnt || ' extra=' || extra || ' missing=' || missing || ')', '; '), '')
    INTO te, tm, bad, det
    FROM p2b_rep WHERE lf_cnt <> al_cnt OR extra <> 0 OR missing <> 0;
  IF te <> 0 OR tm <> 0 OR bad <> 0 THEN
    RAISE EXCEPTION 'P2b LIFETIME_FIXTURE_PATTERN_DRIFT_GATE FAILED: EXTRA_FIXTURE_ROW_COUNT=% ALLOWLIST_MISSING=% drifted_tables=% %', te, tm, bad, det
    USING HINT = 'Fixture-pattern rows outside the 224-row allowlist (e.g. tests re-run against this DB) or changed allowlist rows require a NEW investigation round; this runner never auto-extends its allowlist. Aborted BEFORE any trigger disable and any DELETE: zero writes.';
  END IF;
END $$;

-- ===== P4: no business row references any allowlist row (isolation) =====
DO $$
DECLARE n int := 0;
BEGIN
  SELECT
    (SELECT count(*) FROM domain_role_bindings WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND ((principal_id IN (SELECT principal_id FROM allow_p)) OR (domain_id IN (SELECT domain_id FROM allow_dom))))
  + (SELECT count(*) FROM global_role_bindings WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND principal_id IN (SELECT principal_id FROM allow_p))
  + (SELECT count(*) FROM workflow_definitions WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (domain_id IN (SELECT domain_id FROM allow_dom) OR archived_by_principal_id IN (SELECT principal_id FROM allow_p)))
  + (SELECT count(*) FROM workflow_definition_versions WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def) OR published_by_principal_id IN (SELECT principal_id FROM allow_p) OR deprecated_by_principal_id IN (SELECT principal_id FROM allow_p) OR revoked_by_principal_id IN (SELECT principal_id FROM allow_p)))
  + (SELECT count(*) FROM workflow_node_definitions WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (definition_version_id IN (SELECT definition_version_id FROM allow_ver) OR fixed_principal_id IN (SELECT principal_id FROM allow_p) OR primary_advance_transition_id IN (SELECT transition_id FROM allow_t)))
  + (SELECT count(*) FROM workflow_transition_definitions WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (definition_version_id IN (SELECT definition_version_id FROM allow_ver) OR source_node_id IN (SELECT node_id FROM allow_n) OR target_node_id IN (SELECT node_id FROM allow_n)))
  + (SELECT count(*) FROM workflow_instances WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (domain_id IN (SELECT domain_id FROM allow_dom) OR definition_version_id IN (SELECT definition_version_id FROM allow_ver) OR created_by_principal_id IN (SELECT principal_id FROM allow_p) OR cancelled_by_principal_id IN (SELECT principal_id FROM allow_p) OR archived_by_principal_id IN (SELECT principal_id FROM allow_p)))
  + (SELECT count(*) FROM workflow_node_visits WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) OR node_id IN (SELECT node_id FROM allow_n) OR assignee_principal_id IN (SELECT principal_id FROM allow_p) OR entered_by_transition_id IN (SELECT transition_id FROM allow_t)))
  + (SELECT count(*) FROM workflow_context_revisions WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) OR previous_revision_id IN (SELECT context_revision_id FROM allow_r) OR created_by_principal_id IN (SELECT principal_id FROM allow_p)))
  + (SELECT count(*) FROM workflow_events WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND (workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) OR command_id IN (SELECT command_id FROM allow_c) OR actor_principal_id IN (SELECT principal_id FROM allow_p) OR from_node_id IN (SELECT node_id FROM allow_n) OR to_node_id IN (SELECT node_id FROM allow_n) OR source_node_visit_id IN (SELECT node_visit_id FROM allow_v) OR target_node_visit_id IN (SELECT node_visit_id FROM allow_v) OR context_revision_id IN (SELECT context_revision_id FROM allow_r)))
  + (SELECT count(*) FROM workflow_command_receipts WHERE created_at < '2026-08-29 08:17:36+08'::timestamptz AND principal_id IN (SELECT principal_id FROM allow_p))
  + (SELECT count(*) FROM workflow_command_attempt_audits WHERE command_id IN (SELECT command_id FROM allow_c) OR principal_id IN (SELECT principal_id FROM allow_p))
  + (SELECT count(*) FROM workflow_security_audits WHERE principal_id IN (SELECT principal_id FROM allow_p))
  + (SELECT count(*) FROM workflow_submissions WHERE workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) OR author_principal_id IN (SELECT principal_id FROM allow_p) OR source_node_visit_id IN (SELECT node_visit_id FROM allow_v) OR context_revision_id IN (SELECT context_revision_id FROM allow_r) OR transition_id IN (SELECT transition_id FROM allow_t))
  + (SELECT count(*) FROM workflow_instance_node_assignees WHERE workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) OR assignee_principal_id IN (SELECT principal_id FROM allow_p))
  + (SELECT count(*) FROM workflow_assistance_cases WHERE workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i) OR node_visit_id IN (SELECT node_visit_id FROM allow_v) OR requested_by_principal_id IN (SELECT principal_id FROM allow_p) OR escalated_by_principal_id IN (SELECT principal_id FROM allow_p) OR resolved_by_principal_id IN (SELECT principal_id FROM allow_p) OR voided_by_principal_id IN (SELECT principal_id FROM allow_p) OR request_command_id IN (SELECT command_id FROM allow_c) OR escalation_command_id IN (SELECT command_id FROM allow_c) OR resolution_command_id IN (SELECT command_id FROM allow_c) OR voided_by_command_id IN (SELECT command_id FROM allow_c))
  INTO n;
  IF n <> 0 THEN RAISE EXCEPTION 'P4 isolation: % business rows reference allowlist rows — extra references present, aborting with ZERO writes', n; END IF;
END $$;

-- ===== P5: untouched tables have zero rows in the test window =====
DO $$
DECLARE n int;
BEGIN
  SELECT (SELECT count(*) FROM workflow_submissions WHERE created_at >= '2026-08-29 08:17:36+08'::timestamptz AND created_at < '2026-08-29 08:17:45+08'::timestamptz)
       + (SELECT count(*) FROM workflow_command_attempt_audits WHERE created_at >= '2026-08-29 08:17:36+08'::timestamptz AND created_at < '2026-08-29 08:17:45+08'::timestamptz)
       + (SELECT count(*) FROM workflow_security_audits WHERE created_at >= '2026-08-29 08:17:36+08'::timestamptz AND created_at < '2026-08-29 08:17:45+08'::timestamptz)
       + (SELECT count(*) FROM workflow_instance_node_assignees WHERE created_at >= '2026-08-29 08:17:36+08'::timestamptz AND created_at < '2026-08-29 08:17:45+08'::timestamptz)
       + (SELECT count(*) FROM workflow_assistance_cases WHERE created_at >= '2026-08-29 08:17:36+08'::timestamptz AND created_at < '2026-08-29 08:17:45+08'::timestamptz)
  INTO n;
  IF n <> 0 THEN RAISE EXCEPTION 'P5 untouched tables: % unexpected rows in test window', n; END IF;
END $$;

-- ===== P6: business pre-state digests (non-allowlist rows) =====
CREATE TEMP TABLE dig_pre(t text PRIMARY KEY, cnt bigint, dg text);
INSERT INTO dig_pre SELECT 'principals', count(*), md5(coalesce(string_agg(principal_id::text, ',' ORDER BY principal_id::text), '')) FROM principals WHERE principal_id NOT IN (SELECT principal_id FROM allow_p);
INSERT INTO dig_pre SELECT 'domains', count(*), md5(coalesce(string_agg(domain_id::text, ',' ORDER BY domain_id::text), '')) FROM domains WHERE domain_id NOT IN (SELECT domain_id FROM allow_dom);
INSERT INTO dig_pre SELECT 'domain_role_bindings', count(*), md5(coalesce(string_agg(binding_id::text, ',' ORDER BY binding_id::text), '')) FROM domain_role_bindings WHERE binding_id NOT IN (SELECT binding_id FROM allow_drb);
INSERT INTO dig_pre SELECT 'global_role_bindings', count(*), md5(coalesce(string_agg(binding_id::text, ',' ORDER BY binding_id::text), '')) FROM global_role_bindings WHERE binding_id NOT IN (SELECT binding_id FROM allow_g);
INSERT INTO dig_pre SELECT 'workflow_definitions', count(*), md5(coalesce(string_agg(workflow_definition_id::text, ',' ORDER BY workflow_definition_id::text), '')) FROM workflow_definitions WHERE workflow_definition_id NOT IN (SELECT workflow_definition_id FROM allow_def);
INSERT INTO dig_pre SELECT 'workflow_definition_versions', count(*), md5(coalesce(string_agg(definition_version_id::text, ',' ORDER BY definition_version_id::text), '')) FROM workflow_definition_versions WHERE definition_version_id NOT IN (SELECT definition_version_id FROM allow_ver);
INSERT INTO dig_pre SELECT 'workflow_node_definitions', count(*), md5(coalesce(string_agg(node_id::text, ',' ORDER BY node_id::text), '')) FROM workflow_node_definitions WHERE node_id NOT IN (SELECT node_id FROM allow_n);
INSERT INTO dig_pre SELECT 'workflow_transition_definitions', count(*), md5(coalesce(string_agg(transition_id::text, ',' ORDER BY transition_id::text), '')) FROM workflow_transition_definitions WHERE transition_id NOT IN (SELECT transition_id FROM allow_t);
INSERT INTO dig_pre SELECT 'workflow_instances', count(*), md5(coalesce(string_agg(workflow_instance_id::text, ',' ORDER BY workflow_instance_id::text), '')) FROM workflow_instances WHERE workflow_instance_id NOT IN (SELECT workflow_instance_id FROM allow_i);
INSERT INTO dig_pre SELECT 'workflow_node_visits', count(*), md5(coalesce(string_agg(node_visit_id::text, ',' ORDER BY node_visit_id::text), '')) FROM workflow_node_visits WHERE node_visit_id NOT IN (SELECT node_visit_id FROM allow_v);
INSERT INTO dig_pre SELECT 'workflow_context_revisions', count(*), md5(coalesce(string_agg(context_revision_id::text, ',' ORDER BY context_revision_id::text), '')) FROM workflow_context_revisions WHERE context_revision_id NOT IN (SELECT context_revision_id FROM allow_r);
INSERT INTO dig_pre SELECT 'workflow_events', count(*), md5(coalesce(string_agg(event_id::text, ',' ORDER BY event_id::text), '')) FROM workflow_events WHERE event_id NOT IN (SELECT event_id FROM allow_e);
INSERT INTO dig_pre SELECT 'workflow_command_receipts', count(*), md5(coalesce(string_agg(command_id::text, ',' ORDER BY command_id::text), '')) FROM workflow_command_receipts WHERE command_id NOT IN (SELECT command_id FROM allow_c);
INSERT INTO dig_pre SELECT 'workflow_submissions', count(*), md5(coalesce(string_agg(submission_id::text, ',' ORDER BY submission_id::text), '')) FROM workflow_submissions WHERE TRUE;
INSERT INTO dig_pre SELECT 'workflow_command_attempt_audits', count(*), md5(coalesce(string_agg(audit_id::text, ',' ORDER BY audit_id::text), '')) FROM workflow_command_attempt_audits WHERE TRUE;
INSERT INTO dig_pre SELECT 'workflow_security_audits', count(*), md5(coalesce(string_agg(audit_id::text, ',' ORDER BY audit_id::text), '')) FROM workflow_security_audits WHERE TRUE;
INSERT INTO dig_pre SELECT 'workflow_instance_node_assignees', count(*), md5(coalesce(string_agg(workflow_instance_id::text || '#' || node_key, ',' ORDER BY workflow_instance_id::text || '#' || node_key), '')) FROM workflow_instance_node_assignees WHERE TRUE;
INSERT INTO dig_pre SELECT 'workflow_assistance_cases', count(*), md5(coalesce(string_agg(assistance_case_id::text, ',' ORDER BY assistance_case_id::text), '')) FROM workflow_assistance_cases WHERE TRUE;

-- ===== P7: DELETE-guard triggers present (fail loud if schema drifted) =====
DO $$
DECLARE n int;
BEGIN
  SELECT count(DISTINCT tgname) INTO n FROM pg_trigger WHERE NOT tgisinternal AND tgname IN (
    'trg_events_immutable','trg_context_revisions_immutable','trg_node_visits_immutable',
    'trg_node_definitions_graph_immutable','trg_transition_definitions_graph_immutable',
    'trg_command_receipts_completed_immutable');
  IF n <> 6 THEN RAISE EXCEPTION 'P7: expected 6 DELETE-guard triggers, found %', n; END IF;
END $$;

-- ===== D: FK-safe deletes (exact allowlists only) =====
-- The six append-only DELETE guards are disabled and re-enabled INSIDE this
-- transaction (transactional DDL); any failure rolls the re-enable back too.
ALTER TABLE workflow_events DISABLE TRIGGER trg_events_immutable;
ALTER TABLE workflow_context_revisions DISABLE TRIGGER trg_context_revisions_immutable;
ALTER TABLE workflow_node_visits DISABLE TRIGGER trg_node_visits_immutable;
ALTER TABLE workflow_node_definitions DISABLE TRIGGER trg_node_definitions_graph_immutable;
ALTER TABLE workflow_transition_definitions DISABLE TRIGGER trg_transition_definitions_graph_immutable;
ALTER TABLE workflow_command_receipts DISABLE TRIGGER trg_command_receipts_completed_immutable;

DELETE FROM workflow_events WHERE event_id IN (SELECT event_id FROM allow_e);
DELETE FROM workflow_node_visits WHERE node_visit_id IN (SELECT node_visit_id FROM allow_v);
DELETE FROM workflow_context_revisions WHERE context_revision_id IN (SELECT context_revision_id FROM allow_r);
DELETE FROM workflow_instances WHERE workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i);
DELETE FROM workflow_command_receipts WHERE command_id IN (SELECT command_id FROM allow_c);
DELETE FROM workflow_transition_definitions WHERE transition_id IN (SELECT transition_id FROM allow_t);
DELETE FROM workflow_node_definitions WHERE node_id IN (SELECT node_id FROM allow_n);
DELETE FROM workflow_definition_versions WHERE definition_version_id IN (SELECT definition_version_id FROM allow_ver);
DELETE FROM workflow_definitions WHERE workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def);
DELETE FROM global_role_bindings WHERE binding_id IN (SELECT binding_id FROM allow_g);
DELETE FROM domain_role_bindings WHERE binding_id IN (SELECT binding_id FROM allow_drb);
DELETE FROM domains WHERE domain_id IN (SELECT domain_id FROM allow_dom);
DELETE FROM principals WHERE principal_id IN (SELECT principal_id FROM allow_p);

-- flush all DEFERRED FK checks now (both sides of every cyclic FK are gone,
-- so every check passes); this empties the after-trigger queue so the
-- trigger re-ENABLE ALTERs below are legal.
SET CONSTRAINTS ALL IMMEDIATE;

ALTER TABLE workflow_events ENABLE TRIGGER trg_events_immutable;
ALTER TABLE workflow_context_revisions ENABLE TRIGGER trg_context_revisions_immutable;
ALTER TABLE workflow_node_visits ENABLE TRIGGER trg_node_visits_immutable;
ALTER TABLE workflow_node_definitions ENABLE TRIGGER trg_node_definitions_graph_immutable;
ALTER TABLE workflow_transition_definitions ENABLE TRIGGER trg_transition_definitions_graph_immutable;
ALTER TABLE workflow_command_receipts ENABLE TRIGGER trg_command_receipts_completed_immutable;

-- ===== POST: every allowlist count must be zero =====
DO $$
DECLARE z int;
BEGIN
EXECUTE 'SELECT count(*) FROM principals WHERE principal_id IN (SELECT principal_id FROM allow_p)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST principals: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM domains WHERE domain_id IN (SELECT domain_id FROM allow_dom)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST domains: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM domain_role_bindings WHERE binding_id IN (SELECT binding_id FROM allow_drb)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST domain_role_bindings: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM global_role_bindings WHERE binding_id IN (SELECT binding_id FROM allow_g)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST global_role_bindings: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_definitions WHERE workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_definitions: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_definition_versions WHERE definition_version_id IN (SELECT definition_version_id FROM allow_ver)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_definition_versions: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_node_definitions WHERE node_id IN (SELECT node_id FROM allow_n)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_node_definitions: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_transition_definitions WHERE transition_id IN (SELECT transition_id FROM allow_t)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_transition_definitions: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_instances WHERE workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_instances: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_node_visits WHERE node_visit_id IN (SELECT node_visit_id FROM allow_v)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_node_visits: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_context_revisions WHERE context_revision_id IN (SELECT context_revision_id FROM allow_r)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_context_revisions: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_events WHERE event_id IN (SELECT event_id FROM allow_e)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_events: % allowlist rows remain', z; END IF;
EXECUTE 'SELECT count(*) FROM workflow_command_receipts WHERE command_id IN (SELECT command_id FROM allow_c)' INTO z; IF z <> 0 THEN RAISE EXCEPTION 'POST workflow_command_receipts: % allowlist rows remain', z; END IF;
END $$;

-- ===== POST: business digests unchanged =====
CREATE TEMP TABLE dig_post(t text PRIMARY KEY, cnt bigint, dg text);
INSERT INTO dig_post SELECT 'principals', count(*), md5(coalesce(string_agg(principal_id::text, ',' ORDER BY principal_id::text), '')) FROM principals WHERE principal_id NOT IN (SELECT principal_id FROM allow_p);
INSERT INTO dig_post SELECT 'domains', count(*), md5(coalesce(string_agg(domain_id::text, ',' ORDER BY domain_id::text), '')) FROM domains WHERE domain_id NOT IN (SELECT domain_id FROM allow_dom);
INSERT INTO dig_post SELECT 'domain_role_bindings', count(*), md5(coalesce(string_agg(binding_id::text, ',' ORDER BY binding_id::text), '')) FROM domain_role_bindings WHERE binding_id NOT IN (SELECT binding_id FROM allow_drb);
INSERT INTO dig_post SELECT 'global_role_bindings', count(*), md5(coalesce(string_agg(binding_id::text, ',' ORDER BY binding_id::text), '')) FROM global_role_bindings WHERE binding_id NOT IN (SELECT binding_id FROM allow_g);
INSERT INTO dig_post SELECT 'workflow_definitions', count(*), md5(coalesce(string_agg(workflow_definition_id::text, ',' ORDER BY workflow_definition_id::text), '')) FROM workflow_definitions WHERE workflow_definition_id NOT IN (SELECT workflow_definition_id FROM allow_def);
INSERT INTO dig_post SELECT 'workflow_definition_versions', count(*), md5(coalesce(string_agg(definition_version_id::text, ',' ORDER BY definition_version_id::text), '')) FROM workflow_definition_versions WHERE definition_version_id NOT IN (SELECT definition_version_id FROM allow_ver);
INSERT INTO dig_post SELECT 'workflow_node_definitions', count(*), md5(coalesce(string_agg(node_id::text, ',' ORDER BY node_id::text), '')) FROM workflow_node_definitions WHERE node_id NOT IN (SELECT node_id FROM allow_n);
INSERT INTO dig_post SELECT 'workflow_transition_definitions', count(*), md5(coalesce(string_agg(transition_id::text, ',' ORDER BY transition_id::text), '')) FROM workflow_transition_definitions WHERE transition_id NOT IN (SELECT transition_id FROM allow_t);
INSERT INTO dig_post SELECT 'workflow_instances', count(*), md5(coalesce(string_agg(workflow_instance_id::text, ',' ORDER BY workflow_instance_id::text), '')) FROM workflow_instances WHERE workflow_instance_id NOT IN (SELECT workflow_instance_id FROM allow_i);
INSERT INTO dig_post SELECT 'workflow_node_visits', count(*), md5(coalesce(string_agg(node_visit_id::text, ',' ORDER BY node_visit_id::text), '')) FROM workflow_node_visits WHERE node_visit_id NOT IN (SELECT node_visit_id FROM allow_v);
INSERT INTO dig_post SELECT 'workflow_context_revisions', count(*), md5(coalesce(string_agg(context_revision_id::text, ',' ORDER BY context_revision_id::text), '')) FROM workflow_context_revisions WHERE context_revision_id NOT IN (SELECT context_revision_id FROM allow_r);
INSERT INTO dig_post SELECT 'workflow_events', count(*), md5(coalesce(string_agg(event_id::text, ',' ORDER BY event_id::text), '')) FROM workflow_events WHERE event_id NOT IN (SELECT event_id FROM allow_e);
INSERT INTO dig_post SELECT 'workflow_command_receipts', count(*), md5(coalesce(string_agg(command_id::text, ',' ORDER BY command_id::text), '')) FROM workflow_command_receipts WHERE command_id NOT IN (SELECT command_id FROM allow_c);
INSERT INTO dig_post SELECT 'workflow_submissions', count(*), md5(coalesce(string_agg(submission_id::text, ',' ORDER BY submission_id::text), '')) FROM workflow_submissions WHERE TRUE;
INSERT INTO dig_post SELECT 'workflow_command_attempt_audits', count(*), md5(coalesce(string_agg(audit_id::text, ',' ORDER BY audit_id::text), '')) FROM workflow_command_attempt_audits WHERE TRUE;
INSERT INTO dig_post SELECT 'workflow_security_audits', count(*), md5(coalesce(string_agg(audit_id::text, ',' ORDER BY audit_id::text), '')) FROM workflow_security_audits WHERE TRUE;
INSERT INTO dig_post SELECT 'workflow_instance_node_assignees', count(*), md5(coalesce(string_agg(workflow_instance_id::text || '#' || node_key, ',' ORDER BY workflow_instance_id::text || '#' || node_key), '')) FROM workflow_instance_node_assignees WHERE TRUE;
INSERT INTO dig_post SELECT 'workflow_assistance_cases', count(*), md5(coalesce(string_agg(assistance_case_id::text, ',' ORDER BY assistance_case_id::text), '')) FROM workflow_assistance_cases WHERE TRUE;

DO $$
DECLARE bad int;
BEGIN
  SELECT count(*) INTO bad FROM (
    SELECT p.t, p.cnt AS pre_cnt, q.cnt AS post_cnt, p.dg AS pre_dg, q.dg AS post_dg
    FROM dig_pre p FULL JOIN dig_post q USING (t)
    WHERE p.cnt IS DISTINCT FROM q.cnt OR p.dg IS DISTINCT FROM q.dg
  ) d;
  IF bad <> 0 THEN
    RAISE EXCEPTION 'POST digest mismatch on % table(s) — rolling back everything', bad;
  END IF;
END $$;

\if :dryrun
\echo ''
\echo 'DRYRUN: pre-checks, guarded deletes, and ALL post-checks executed inside the transaction.'
\echo 'DRYRUN: rolling back now — ZERO writes will be committed.'
ROLLBACK;
\quit
\endif

COMMIT;

\echo ''
\echo 'CLEANUP COMMITTED. Remaining counts (all must be 0):'
SELECT 'principals' AS what, count(*) AS remaining FROM principals WHERE principal_id IN (SELECT principal_id FROM allow_p)
UNION ALL SELECT 'domains', count(*) FROM domains WHERE domain_id IN (SELECT domain_id FROM allow_dom)
UNION ALL SELECT 'domain_role_bindings', count(*) FROM domain_role_bindings WHERE binding_id IN (SELECT binding_id FROM allow_drb)
UNION ALL SELECT 'global_role_bindings', count(*) FROM global_role_bindings WHERE binding_id IN (SELECT binding_id FROM allow_g)
UNION ALL SELECT 'workflow_definitions', count(*) FROM workflow_definitions WHERE workflow_definition_id IN (SELECT workflow_definition_id FROM allow_def)
UNION ALL SELECT 'workflow_definition_versions', count(*) FROM workflow_definition_versions WHERE definition_version_id IN (SELECT definition_version_id FROM allow_ver)
UNION ALL SELECT 'workflow_node_definitions', count(*) FROM workflow_node_definitions WHERE node_id IN (SELECT node_id FROM allow_n)
UNION ALL SELECT 'workflow_transition_definitions', count(*) FROM workflow_transition_definitions WHERE transition_id IN (SELECT transition_id FROM allow_t)
UNION ALL SELECT 'workflow_instances', count(*) FROM workflow_instances WHERE workflow_instance_id IN (SELECT workflow_instance_id FROM allow_i)
UNION ALL SELECT 'workflow_node_visits', count(*) FROM workflow_node_visits WHERE node_visit_id IN (SELECT node_visit_id FROM allow_v)
UNION ALL SELECT 'workflow_context_revisions', count(*) FROM workflow_context_revisions WHERE context_revision_id IN (SELECT context_revision_id FROM allow_r)
UNION ALL SELECT 'workflow_events', count(*) FROM workflow_events WHERE event_id IN (SELECT event_id FROM allow_e)
UNION ALL SELECT 'workflow_command_receipts', count(*) FROM workflow_command_receipts WHERE command_id IN (SELECT command_id FROM allow_c);
SQLEOF
status=${PIPESTATUS[0]}
set -e
echo
if [ "$status" -ne 0 ]; then
  echo "RESULT: FAILED (transaction rolled back; zero rows committed). See $LOG"
  exit "$status"
fi
if [ "$DRYRUN" = "1" ]; then
  echo "RESULT: DRYRUN PASSED — all pre-checks green, rolled back, zero writes."
else
  echo "RESULT: CLEANUP COMMITTED. Full transcript: $LOG"
fi
