#!/bin/bash
# Agent Core COMBINED production deploy runner v2 (AUTHORING ONLY; not executed
# by the authoring round beyond read-only --check).
#
# ONE DEPLOY + ONE AGENT CORE RELOAD carrying BOTH:
#   A. the pending accepted Workflow Broker delta
#        - workflow_transition        (AGENT_CORE_WORKFLOW_ASSIGNEE_TRANSITION_CAPABILITY_V1,
#                                      accepted / implementation_authority: contracts,
#                                      implementation merged via PR #125 -> 1aa8248)
#        - Domain pagination successor (AGENT_CORE_WORKFLOW_DOMAIN_INSTANCES_PAGINATION_V2,
#                                      accepted / contracts, merged via PR #126 -> 4d7ca24)
#        - Broker Error Preservation discipline (AGENT_CORE_WORKFLOW_BROKER_ERROR_PRESERVATION_V1,
#                                      accepted; its own implementation already deployed at
#                                      PR #82; this delta keeps the family, incl. the V2
#                                      sanitizer restated by CTR-FMC-012)
#   B. the freshly merged Forum Broker delta
#        (AGENT_CORE_FORUM_MODERATION_CAPABILITIES_V2, accepted / contracts,
#         implementation merged via PR #105 -> 2392a41 == TARGET_MAIN itself)
#
# TARGET_MAIN = 2392a41d4655ba25ed9e9749fbf8beb0ad1c71b4 (fresh github/main after
# the Forum merge; runner refuses if main has moved — re-audit required).
#
# AUTHORIZED_DEPLOYMENT_FILES (fresh-derived 2026-08-31 census live->TARGET_MAIN,
# NOT hardcoded from any older round; every file traces to an accepted Spec with
# implementation_authority: contracts + a merged implementation):
#   modified (6, inside the app manifest):
#     packages/broker/src/capabilities/workflow.js   04ca8550 -> 83df50eb  (PR #125 + #126)
#     packages/broker/src/mapping.js                 890d35b9 -> 74e83e11  (PR #125 + #126 + #105)
#     packages/broker/src/schema.js                  13f80f87 -> 1bd36bbe  (PR #125 + #126 + #105)
#     packages/broker/src/capabilities/forum.js      f068c171 -> b64b7357  (PR #105)
#     packages/broker/src/index.js                   6c4a60af -> a543e586  (PR #105)
#     packages/broker/src/transport.js               b697850c -> 942e9880  (PR #105)
#   new (2, inside the app manifest):
#     packages/broker/src/capabilities/forum-moderation.js   (new) -> 90cf87c3  (PR #105)
#     packages/broker/src/error-detail-sanitizer.js          (new) -> 25e02239  (PR #105)
#   modified (1, OUTSIDE the manifest because bundle-* is pruned; pinned by its
#   own blob OID; enters production through the NORMAL bundle build flow — the
#   per-agent child composition resolves bundle-broker via the repo farm link):
#     bundle-broker/cordis.patch.yml                 b84c6296 -> 768ddec  (PR #105,
#                                                                     CTR-FMC-004/014)
#
# EXCLUDED_DRIFT (live != TARGET_MAIN but NEVER written by this runner; each is
# pinned at its live OID and ANY drift in either direction fails closed):
#   packages/production-runtime/src/model-overrides.js  live ea44819a (main f1e09d47)
#     — emergency breakglass, pending Owner ratification; NEVER written.
#   packages/feishu-connector/src/index.js              live 2e6bd089 (main bd3b0e5b)
#     — 9386ac4 scheduler-success Feishu cards; NO deployment authority here.
#   packages/scheduler-router/src/index.js              live b1f55634 (main c05c6087)
#     — 9386ac4 scheduler-success Feishu cards; NO deployment authority here.
# Test files are NOT production delta (none exist in the live app manifest).
# Credentials, identity stores, svc-workflow and the Forum server are untouched.
#
# CANARY PREREQUISITE (fail closed): the fixed-path config
#   /tmp/agent-core-workflow-canary-v1.json
# generated by the separate canary-prep task must exist, parse, carry no
# placeholder and no secret, pin exact baselines, and its canary identity must
# equal the accepted CTR-009 default canary identity `agt_build-in-public-agent`.
# If CANARY_PREREQS_READY != YES then --check FAILS (exit 2) and --apply refuses
# before any write. --apply additionally takes the config sha256 printed by
# --check and refuses on any byte mismatch (reviewed config == applied config).
#
# Success path: durable backup -> 9 atomic durable installs (7 replace + 2 new)
# -> post-deploy workflow transition canary against the INSTALLED files (before
# the reload; canary failure rolls disk back without reloading) -> exactly ONE
# reload (launchctl kickstart -k system/ai.agent-core.runtime) -> health ->
# post-reload combined smoke (workflow + forum normal + moderator visibility)
# -> durable receipt + ledger. A failure after the one success-path reload may
# require one additional recovery reload after a durable rollback; that
# exception is reported explicitly (rollback reload).
#
# Inherited audited mechanisms: root gate, explicit owner phrase, pre-manifest
# SHA, exact source blob pins, exact file closure, breakglass pin, lstat/symlink
# guard, stage, backup, fsync, byte verification, install, ONE reload,
# post-manifest verification, workflow canary, idempotent replay, control
# instance unchanged, rollback, rollback reload, ROLLBACK_INCOMPLETE, durable
# receipt, rerun NOOP, secret zero output.
set -Eeuo pipefail

readonly REPO_ROOT="/Users/yanfenma/workspace/project/dsh-agent-core"
readonly TARGET_COMMIT="2392a41d4655ba25ed9e9749fbf8beb0ad1c71b4"
readonly TRANSITION_MERGE="1aa8248893766aaf1caae17b2905e40061f0a147"
readonly PAGINATION_MERGE="4d7ca245ec0b9f6ed8a650f742b94b39728331a7"
readonly FORUM_MERGE="2392a41d4655ba25ed9e9749fbf8beb0ad1c71b4"
readonly FORUM_IMPL_HEAD="83165dea530956a8836e9830c54811eb3a8ae93e"
readonly TRUSTED_ROOT="/usr/local/libexec/agent-core"
readonly LIVE_ROOT="$TRUSTED_ROOT/app"
readonly BACKUP_ROOT="$TRUSTED_ROOT/.deploy-backups"
readonly LEDGER="$BACKUP_ROOT/agent-core-deploy-ledger.log"
readonly CREDENTIALS_FILE="$TRUSTED_ROOT/config/agent-credentials.json"
readonly AUTH_ORIGIN="http://127.0.0.1:4001"
readonly WORKFLOW_ORIGIN="http://127.0.0.1:8989"
readonly PLIST_PATH="/Library/LaunchDaemons/ai.agent-core.runtime.plist"
readonly SERVICE_LABEL="system/ai.agent-core.runtime"
readonly HEALTH_URL="http://127.0.0.1:8790/health"
readonly CONFIRM_PHRASE="APPLY AGENT_CORE_COMBINED_DEPLOY_V1"
readonly CANARY_CONFIG="/tmp/agent-core-workflow-canary-v1.json"
readonly GIT=/usr/bin/git
readonly SHASUM=/usr/bin/shasum
readonly PYTHON3=/usr/bin/python3
readonly NODE="$TRUSTED_ROOT/node-runtime/bin/node"

readonly BREAKGLASS_PATH="packages/production-runtime/src/model-overrides.js"
readonly BREAKGLASS_OID="ea44819a18085c6bd8665157d92caba205e720d9"
readonly EXCLUDED_PIN_PATHS="packages/feishu-connector/src/index.js
packages/scheduler-router/src/index.js"
readonly EXCLUDED_PIN_OIDS="2e6bd0896dd0354877aebc99361a986a05c1e06a
b1f5563411cb55c8ddc3391d6337a30aea2e0f45"

readonly BASE_FILE_COUNT="132"
readonly BASE_MANIFEST_SHA256="9ac84954fefc3d5893b7e5ca7045b2bb7cf0ad7492d121607d2b0659a230f4b1"
readonly TARGET_FILE_COUNT="134"
readonly TARGET_MANIFEST_SHA256="865b6569591e361b18ffcde01251c0b2c2ba160818a0738127a2e8a0bcf2a8d6"

# Exact authorized closure (fresh-derived census 2026-08-31; order is fixed and
# index-aligned across DELTA_PATHS / BASE_OIDS / TARGET_OIDS). ABSENT in
# BASE_OIDS marks a file that must NOT exist in the BASE state (new file).
readonly DELTA_COUNT=9
readonly DELTA_PATHS="packages/broker/src/capabilities/workflow.js
packages/broker/src/mapping.js
packages/broker/src/schema.js
packages/broker/src/capabilities/forum.js
packages/broker/src/capabilities/forum-moderation.js
packages/broker/src/error-detail-sanitizer.js
packages/broker/src/index.js
packages/broker/src/transport.js
bundle-broker/cordis.patch.yml"
readonly BASE_OIDS="04ca8550fbdaf9b66624dea42701a8a9af7547a8
890d35b97700e741b0b6960049b619da03645483
13f80f87ce3591669224a061a243fa6cce96a553
f068c171c2c8bd66b774c197bdbae09d1bcf809b
ABSENT
ABSENT
6c4a60af4c529dd052ad45bd641213d40ee6800c
b697850cfd1961ac7ee88aa625d0a5c711aa7eac
b84c629679e900ea886896c9656c8ecb9fb792ae"
readonly TARGET_OIDS="83df50eb9947c865a2df531b05285c5e0f3eae0c
74e83e11660a0ea5a9dffc47fe2a8897f17f9809
1bd36bbe5f3fc796dffdf633b557fbb7fff2741b
b64b73578f9645777025d8bff74e82f551de3866
90cf87c3e4afd424574b4f18b12742306c5968df
25e02239255f95c55e59454bd32703550e3ad5b0
a543e586792aa18c592b7d2afb535b4ff575d286
942e9880ff11fbc672481f66f7e96d35778dfc4f
768ddecaea5fedabe3c44cb63c11926cdfb2b885"

DETECTED_STATE=""
RESTART_COUNT=0
CANARY_READY="NO"
CANARY_CONFIG_SHA256=""
fail() { echo "ERROR: $*" >&2; exit 2; }
hash_file() { "$GIT" -C "$REPO_ROOT" hash-object "$1"; }
line_at() { printf '%s\n' "$1" | /usr/bin/sed -n "${2}p"; }

write_manifest() {
  local root="$1" output="$2" path
  [ -d "$root" ] || return 1
  (
    cd "$root"
    /usr/bin/find . \( -path './node_modules' -o -path './bundle-*' -o -path './profile-*' \) -prune -o -type f -print \
      | /usr/bin/sed 's#^\./##' | LC_ALL=C /usr/bin/sort
  ) | while IFS= read -r path; do
    printf '%s  %s\n' "$(hash_file "$root/$path")" "$path"
  done > "$output"
}

verify_tree_status() {
  local root="$1" manifest count digest actual path expected i
  manifest="$(/usr/bin/mktemp "${TMPDIR:-/tmp}/ac-combined-manifest.XXXXXX")" || return 1
  if ! write_manifest "$root" "$manifest"; then /bin/rm -f "$manifest"; return 1; fi
  count="$(/usr/bin/wc -l < "$manifest" | /usr/bin/tr -d ' ')"
  digest="$("$SHASUM" -a 256 "$manifest" | /usr/bin/awk '{print $1}')"
  /bin/rm -f "$manifest"
  if [ "$count" = "$BASE_FILE_COUNT" ] && [ "$digest" = "$BASE_MANIFEST_SHA256" ]; then
    DETECTED_STATE="BASE"
    expected="$BASE_OIDS"
  elif [ "$count" = "$TARGET_FILE_COUNT" ] && [ "$digest" = "$TARGET_MANIFEST_SHA256" ]; then
    DETECTED_STATE="TARGET"
    expected="$TARGET_OIDS"
  else
    echo "ERROR: unapproved app manifest: count=$count sha256=$digest" >&2
    return 1
  fi
  i=1
  while [ "$i" -le "$DELTA_COUNT" ]; do
    path="$(line_at "$DELTA_PATHS" "$i")"
    if [ "$(line_at "$expected" "$i")" = "ABSENT" ]; then
      if [ "$DETECTED_STATE" = "BASE" ] && [ -e "$root/$path" ]; then
        echo "ERROR: new-file path already exists in BASE state: $path" >&2
        return 1
      fi
    else
      actual="$(hash_file "$root/$path")" || return 1
      [ "$actual" = "$(line_at "$expected" "$i")" ] || {
        echo "ERROR: delta path mismatch: $path state=$DETECTED_STATE expected=$(line_at "$expected" "$i") actual=$actual" >&2
        return 1
      }
    fi
    i=$((i + 1))
  done
  actual="$(hash_file "$root/$BREAKGLASS_PATH")" || return 1
  [ "$actual" = "$BREAKGLASS_OID" ] || {
    echo "ERROR: breakglass model-overrides drifted; refusing every write: expected=$BREAKGLASS_OID actual=$actual" >&2
    return 1
  }
  i=1
  while [ "$i" -le 2 ]; do
    path="$(line_at "$EXCLUDED_PIN_PATHS" "$i")"
    actual="$(hash_file "$root/$path")" || return 1
    [ "$actual" = "$(line_at "$EXCLUDED_PIN_OIDS" "$i")" ] || {
      echo "ERROR: excluded unauthorized drift file changed ($path expected=$(line_at "$EXCLUDED_PIN_OIDS" "$i") actual=$actual); this runner never writes it — re-audit required" >&2
      return 1
    }
    i=$((i + 1))
  done
}

verify_tree() {
  local root="$1" required="${2:-EITHER}"
  verify_tree_status "$root" || fail "tree verification failed: $root"
  [ "$required" = "EITHER" ] || [ "$DETECTED_STATE" = "$required" ] \
    || fail "tree state=$DETECTED_STATE expected=$required"
}

verify_source_authority() {
  local main actual path i
  [ -d "$REPO_ROOT/.git" ] || fail "repo checkout missing: $REPO_ROOT"
  "$GIT" -C "$REPO_ROOT" fetch github main >/dev/null 2>&1 \
    || fail "fresh github/main fetch failed"
  main="$("$GIT" -C "$REPO_ROOT" rev-parse github/main)"
  [ "$main" = "$TARGET_COMMIT" ] || fail "fresh main moved: expected=$TARGET_COMMIT actual=$main; re-audit required"
  "$GIT" -C "$REPO_ROOT" merge-base --is-ancestor "$TRANSITION_MERGE" "$main" \
    || fail "workflow_transition merge absent from fresh main"
  "$GIT" -C "$REPO_ROOT" merge-base --is-ancestor "$PAGINATION_MERGE" "$main" \
    || fail "pagination merge absent from fresh main"
  "$GIT" -C "$REPO_ROOT" merge-base --is-ancestor "$FORUM_IMPL_HEAD" "$main" \
    || fail "forum implementation head absent from fresh main"
  i=1
  while [ "$i" -le "$DELTA_COUNT" ]; do
    path="$(line_at "$DELTA_PATHS" "$i")"
    actual="$("$GIT" -C "$REPO_ROOT" rev-parse "$TARGET_COMMIT:$path")"
    [ "$actual" = "$(line_at "$TARGET_OIDS" "$i")" ] || fail "target blob mismatch: $path ($actual)"
    i=$((i + 1))
  done
}

service_preflight() {
  local path p owner mode i=1
  [ -x "$PYTHON3" ] || fail "python3 unavailable"
  [ -x "$NODE" ] || fail "node unavailable: $NODE"
  [ ! -L "$LIVE_ROOT" ] || fail "live app root is a symlink"
  [ -f "$PLIST_PATH" ] || fail "launchd plist missing"
  [ -d "$BACKUP_ROOT" ] && [ ! -L "$BACKUP_ROOT" ] || fail "pre-existing backup root missing or symlinked: $BACKUP_ROOT"
  [ -f "$CREDENTIALS_FILE" ] && [ ! -L "$CREDENTIALS_FILE" ] || fail "credential store missing or symlinked"
  /bin/launchctl print "$SERVICE_LABEL" >/dev/null 2>&1 || fail "runtime service unavailable"
  /usr/bin/curl -fsS --max-time 3 "$HEALTH_URL" >/dev/null 2>&1 || fail "runtime unhealthy before deploy"
  while [ "$i" -le "$DELTA_COUNT" ]; do
    path="$(line_at "$DELTA_PATHS" "$i")"; p="$LIVE_ROOT/$path"
    if [ "$(line_at "$BASE_OIDS" "$i")" = "ABSENT" ]; then
      if [ -e "$p" ] || [ -L "$p" ]; then
        fail "new-file path already exists (unexpected state): $path"
      fi
    else
      [ -f "$p" ] && [ ! -L "$p" ] || fail "delta path is not a regular file: $path"
      owner="$(/usr/bin/stat -f '%u:%g' "$p")"; mode="$(/usr/bin/stat -f '%Lp' "$p")"
      [ "$owner" = "0:0" ] && [ "$mode" = "644" ] || fail "unexpected owner/mode: $path ($owner $mode)"
    fi
    i=$((i + 1))
  done
}

fsync_file() {
  "$PYTHON3" - "$1" <<'PY'
import os, sys
flags = os.O_RDONLY | (getattr(os, 'O_NOFOLLOW', 0))
fd = os.open(sys.argv[1], flags)
try: os.fsync(fd)
finally: os.close(fd)
PY
}

fsync_directory() {
  "$PYTHON3" - "$1" <<'PY'
import os, sys
flags = os.O_RDONLY | (getattr(os, 'O_DIRECTORY', 0))
fd = os.open(sys.argv[1], flags)
try: os.fsync(fd)
finally: os.close(fd)
PY
}

fsync_directory_chain() {
  # fsync_directory_chain <leaf-dir> <owned-stop-dir>, inclusive.
  local current="$1" stop="$2"
  case "$current/" in "$stop/"*) ;; *) return 1 ;; esac
  while :; do
    fsync_directory "$current" || return 1
    [ "$current" = "$stop" ] && break
    current="$(dirname "$current")"
  done
}

atomic_install() {
  local source="$1" target="$2" mode="$3" uid="$4" gid="$5" dir base tmp
  dir="$(dirname "$target")"; base="$(basename "$target")"; tmp="$dir/.${base}.combined-v2.$$"
  /usr/bin/install -m "$mode" -o "$uid" -g "$gid" "$source" "$tmp" || { /bin/rm -f "$tmp"; return 1; }
  fsync_file "$tmp" || { /bin/rm -f "$tmp"; return 1; }
  /bin/mv -f "$tmp" "$target" || { /bin/rm -f "$tmp"; return 1; }
  fsync_directory "$dir"
}

wait_for_health() {
  local n=0
  while [ "$n" -lt 45 ]; do
    /usr/bin/curl -fsS --max-time 2 "$HEALTH_URL" >/dev/null 2>&1 && return 0
    /bin/sleep 2; n=$((n + 1))
  done
  return 1
}

# CANARY PREREQ VALIDATION (fail closed). Prints CANARY_* lines; never prints
# config bytes. The python helper always exits 0 and reports readiness on
# stdout; this wrapper captures it into globals. Any internal crash leaves
# CANARY_READY=NO (fail closed).
validate_canary_prereqs() {
  CANARY_READY="NO"; CANARY_CONFIG_SHA256=""
  local out
  out="$("$PYTHON3" - "$CANARY_CONFIG" <<'PY'
import hashlib, json, os, re, stat as statmod, sys

path = sys.argv[1]
issues = []

def emit(line):
    print(line)

def ready(flag):
    emit(f'CANARY_PREREQS_READY={"YES" if flag else "NO"}')

try:
    st = os.lstat(path)
except FileNotFoundError:
    emit('CANARY_ISSUE=file_missing: ' + path)
    ready(False)
    sys.exit(0)
if statmod.S_ISLNK(st.st_mode):
    emit('CANARY_ISSUE=symlink_refused')
    ready(False)
    sys.exit(0)
if not statmod.S_ISREG(st.st_mode):
    emit('CANARY_ISSUE=not_a_regular_file')
    ready(False)
    sys.exit(0)
if st.st_size == 0:
    emit('CANARY_ISSUE=empty_file')
    ready(False)
    sys.exit(0)
try:
    with open(path, 'rb') as fh:
        raw = fh.read()
except OSError as exc:
    emit(f'CANARY_ISSUE=unreadable: {type(exc).__name__}')
    ready(False)
    sys.exit(0)

emit(f'CANARY_CONFIG_SHA256={hashlib.sha256(raw).hexdigest()}')

text = raw.decode('utf-8', errors='replace')

PLACEHOLDER_RES = [
    r'PLACEHOLDER', r'\bTODO\b', r'\bTBD\b', r'\bFIXME\b', r'CHANGE_?ME',
    r'<[A-Za-z_][A-Za-z0-9_-]*>', r'example\.(com|org)', r'\byour[-_][a-z]', r'\bXXX{2,}\b',
]
for pattern in PLACEHOLDER_RES:
    m = re.search(pattern, text, re.IGNORECASE)
    if m:
        issues.append(f'placeholder_pattern={pattern}')

SECRET_RES = [
    r'-----BEGIN [A-Z ]*PRIVATE KEY-----',
    r'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{5,}',
    r'[A-Fa-f0-9]{48,}',
    r'[A-Za-z0-9+/]{44,}={0,2}',
]
for pattern in SECRET_RES:
    if re.search(pattern, text):
        issues.append(f'secret_pattern={pattern}')
if re.search(r'"(client_?secret|access_?token|refresh_?token|api_?key|password|private_?key|token|secret)"\s*:\s*"[^"]+"', text, re.IGNORECASE):
    issues.append('secret_key_with_value')

try:
    cfg = json.loads(text)
except Exception as exc:
    emit(f'CANARY_ISSUE=json_parse_failed: {type(exc).__name__}')
    for i in issues:
        emit(f'CANARY_ISSUE={i}')
    ready(False)
    sys.exit(0)

REQUIRED_STRINGS = [
    'agentId', 'domainId', 'canaryInstanceId', 'controlInstanceId',
    'expectedAssigneePrincipalId', 'expectedCanaryTitle', 'transitionDefinitionId',
]
for key in REQUIRED_STRINGS:
    v = cfg.get(key)
    if not isinstance(v, str) or v.strip() == '':
        issues.append(f'missing_or_empty={key}')

# CTR-009 canary identity: default (and currently the only) canary identity.
if cfg.get('agentId') != 'agt_build-in-public-agent':
    issues.append('canary_identity_not_ctr009_default (expected agt_build-in-public-agent)')

UUID_RE = re.compile(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', re.IGNORECASE)
for key in ['domainId', 'canaryInstanceId', 'controlInstanceId', 'expectedAssigneePrincipalId', 'transitionDefinitionId']:
    v = cfg.get(key)
    if isinstance(v, str) and not UUID_RE.match(v):
        issues.append(f'not_a_uuid={key}')

if cfg.get('dedicatedNoBusinessSideEffects') is not True:
    issues.append('dedicatedNoBusinessSideEffects_not_true')
if cfg.get('canaryInstanceId') == cfg.get('controlInstanceId'):
    issues.append('control_instance_equals_canary_instance')
if not re.search(r'canary', str(cfg.get('expectedCanaryTitle', '')), re.IGNORECASE):
    issues.append('canary_title_not_marked')

sv = cfg.get('expectedWorkflowStateVersion')
if not isinstance(sv, int) or isinstance(sv, bool) or sv < 1:
    issues.append('expectedWorkflowStateVersion_invalid (integer >= 1)')

limit = cfg.get('paginationLimit', 2)
if not isinstance(limit, int) or isinstance(limit, bool) or not (1 <= limit <= 20):
    issues.append('paginationLimit_invalid (integer 1..20)')
pages = cfg.get('expectedMinimumPages')
if not isinstance(pages, int) or isinstance(pages, bool) or pages < 2:
    issues.append('expectedMinimumPages_invalid (integer >= 2)')
inst = cfg.get('expectedMinimumInstances')
if not isinstance(inst, int) or isinstance(inst, bool) or (isinstance(limit, int) and inst is not None and inst <= limit):
    issues.append('expectedMinimumInstances_invalid (must exceed one page)')

if 'submissionPayload' in cfg and not isinstance(cfg['submissionPayload'], dict):
    issues.append('submissionPayload_not_object')

# Schema baseline sanity: submission schema keys, if provided, must be strings.
schema_baseline = cfg.get('expectedSubmissionSchemaKeys')
if schema_baseline is not None and not (isinstance(schema_baseline, list) and all(isinstance(k, str) for k in schema_baseline)):
    issues.append('expectedSubmissionSchemaKeys_invalid')

for i in issues:
    emit(f'CANARY_ISSUE={i}')
ready(not issues)
PY
)" || out=""
  printf '%s\n' "$out"
  CANARY_CONFIG_SHA256="$(printf '%s\n' "$out" | /usr/bin/sed -n 's/^CANARY_CONFIG_SHA256=//p' | /usr/bin/head -n 1)"
  CANARY_READY="$(printf '%s\n' "$out" | /usr/bin/sed -n 's/^CANARY_PREREQS_READY=//p' | /usr/bin/head -n 1)"
  [ -n "$CANARY_READY" ] || CANARY_READY="NO"
}

# Post-deploy workflow transition canary. Runs against the INSTALLED files in a
# separate Node process BEFORE the single reload (canary failure => durable
# rollback with zero reloads). Audited v1 program + CTR-009 acceptance
# assertions (V+1 / eventSequence / node-visit change / detail re-read).
write_canary_program() {
  local output="$1"
  cat > "$output" <<'NODE'
import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'

const [appRoot, credentialsFile, authOrigin, workflowOrigin, configPath] = process.argv.slice(2)
const cfg = JSON.parse(await readFile(configPath, 'utf8'))
for (const key of ['agentId','domainId','canaryInstanceId','controlInstanceId','expectedAssigneePrincipalId','expectedCanaryTitle','transitionDefinitionId','expectedWorkflowStateVersion','expectedMinimumPages','expectedMinimumInstances']) {
  assert.ok(cfg[key] !== undefined && cfg[key] !== '', `missing canary config field: ${key}`)
}
assert.equal(cfg.dedicatedNoBusinessSideEffects, true, 'canary config must attest dedicatedNoBusinessSideEffects=true')
assert.notEqual(cfg.canaryInstanceId, cfg.controlInstanceId, 'control instance must differ from canary instance')
assert.match(cfg.expectedCanaryTitle, /canary/i, 'dedicated instance title must visibly contain canary')
assert.equal(cfg.agentId, 'agt_build-in-public-agent', 'canary identity must equal the accepted CTR-009 default canary identity')
const limit = cfg.paginationLimit ?? 2
assert.ok(Number.isInteger(limit) && limit >= 1 && limit <= 20)
assert.ok(Number.isInteger(cfg.expectedMinimumPages) && cfg.expectedMinimumPages >= 2, 'canary must require at least two pages')
assert.ok(Number.isInteger(cfg.expectedMinimumInstances) && cfg.expectedMinimumInstances > limit, 'fixture must contain more instances than one page')

let capturedTransition
const realFetch = globalThis.fetch
globalThis.fetch = async (url, init = {}) => {
  const u = String(url)
  if (u === `${workflowOrigin}/internal/v1/workflow-instances/${cfg.canaryInstanceId}/transitions` && init.method === 'POST') {
    const headers = new Headers(init.headers)
    capturedTransition = {
      url: u,
      method: init.method,
      authorization: headers.get('authorization'),
      idempotencyKey: headers.get('idempotency-key'),
      contentType: headers.get('content-type'),
      accept: headers.get('accept'),
      body: init.body,
    }
    const response = await realFetch(url, init)
    const copy = response.clone()
    capturedTransition.firstStatus = copy.status
    capturedTransition.firstContentType = copy.headers.get('content-type')
    capturedTransition.firstBody = new Uint8Array(await copy.arrayBuffer())
    return response
  }
  return realFetch(url, init)
}

const [{ createBrokerGateway }, { manifests }, { targets }] = await Promise.all([
  import(pathToFileURL(`${appRoot}/packages/broker/src/gateway.js`)),
  import(pathToFileURL(`${appRoot}/packages/broker/src/capabilities/workflow.js`)),
  import(pathToFileURL(`${appRoot}/packages/broker/src/targets.js`)),
])
const ids = new Set(manifests.map((m) => m.id))
assert.ok(ids.has('workflow_transition'))
assert.ok(ids.has('workflow_domain_instances'))
assert.ok(ids.has('workflow_global_instances'))
const gateway = createBrokerGateway({ manifests, targets, authServiceOrigin: authOrigin, credentialsFile })
const execute = async (capabilityId, operation, args) => {
  const out = await gateway.execute({ capabilityId, operation, args }, { agentId: cfg.agentId })
  assert.equal(out?.ok, true, `${capabilityId}.${operation} failed: ${JSON.stringify(out?.error ?? out)}`)
  return out.result
}
const detail = (id) => execute('workflow_instance_detail', 'read', { workflowInstanceId: id })
const paginateDomain = async () => {
  const itemsById = new Map(), cursorsSeen = new Set()
  let cursor, pages = 0
  for (;;) {
    const page = await execute('workflow_domain_instances', 'list', {
      domainId: cfg.domainId,
      limit,
      ...(cursor ? { beforeCreatedAt: cursor.created_at, beforeId: cursor.id } : {}),
    })
    assert.ok(Array.isArray(page?.items), 'domain page items missing')
    for (const item of page.items) {
      const id = item.workflow_instance_id ?? item.workflowInstanceId
      assert.ok(typeof id === 'string' && id !== '', 'domain item id missing')
      assert.equal(itemsById.has(id), false, `duplicate workflow instance across pages: ${id}`)
      itemsById.set(id, item)
    }
    pages += 1
    assert.ok(pages <= 1000, 'pagination did not terminate within 1000 pages')
    if (page.next_cursor === null) { cursor = null; break }
    cursor = page.next_cursor
    assert.ok(cursor && typeof cursor.created_at === 'string' && typeof cursor.id === 'string', 'next_cursor is not a complete pair')
    const cursorKey = `${cursor.created_at}\u0000${cursor.id}`
    assert.equal(cursorsSeen.has(cursorKey), false, 'pagination cursor repeated')
    cursorsSeen.add(cursorKey)
  }
  assert.equal(cursor, null)
  return { itemsById, pages }
}

// Canary 1: walk every domain page, reject duplicate ids/cursors, require terminal null cursor.
const domainBefore = await paginateDomain()
assert.ok(domainBefore.pages >= cfg.expectedMinimumPages, `pagination fixture produced only ${domainBefore.pages} pages`)
assert.ok(domainBefore.itemsById.size >= cfg.expectedMinimumInstances, `pagination fixture produced only ${domainBefore.itemsById.size} instances`)
assert.ok(domainBefore.itemsById.has(cfg.canaryInstanceId), 'dedicated canary instance is absent from paginated domain')
assert.ok(domainBefore.itemsById.has(cfg.controlInstanceId), 'control instance is absent from paginated domain')

// Canary 2: exact-assignee dedicated fixture; first call through workflow_transition,
// then replay the captured trusted key directly and require byte-equivalent JSON.
const before = await detail(cfg.canaryInstanceId)
const controlBefore = await detail(cfg.controlInstanceId)
assert.equal(before.title, cfg.expectedCanaryTitle)
const assignee = before.current_assignee_principal_id ?? before.currentAssigneePrincipalId ?? before.current_node_visit?.assignee_principal_id ?? before.currentNodeVisit?.assigneePrincipalId
assert.equal(assignee, cfg.expectedAssigneePrincipalId, 'canary caller is not the pinned exact assignee')
const stateVersion = before.workflow_state_version ?? before.workflowStateVersion
assert.equal(stateVersion, cfg.expectedWorkflowStateVersion, 'canary initial state version drifted')
const outgoing = before.outgoing_transitions ?? before.outgoingTransitions ?? []
const selected = outgoing.find((t) => (t.transition_id ?? t.transitionId) === cfg.transitionDefinitionId)
assert.ok(selected, 'pinned transition is not outgoing from the canary instance')
assert.equal(selected.executable_for_actor ?? selected.executableForActor, true, 'pinned transition is not executable for exact assignee')
const beforeNodeVisitId = before.current_node_visit?.node_visit_id ?? before.current_node_visit?.id ?? before.currentNodeVisit?.nodeVisitId ?? before.currentNodeVisit?.id ?? null

const first = await execute('workflow_transition', 'submit', {
  workflowInstanceId: cfg.canaryInstanceId,
  transitionDefinitionId: cfg.transitionDefinitionId,
  expectedWorkflowStateVersion: cfg.expectedWorkflowStateVersion,
  ...(Object.prototype.hasOwnProperty.call(cfg, 'submissionPayload') ? { submissionPayload: cfg.submissionPayload } : {}),
})
assert.ok(capturedTransition?.authorization?.startsWith('Bearer '), 'transition authorization was not captured')
assert.match(capturedTransition.idempotencyKey ?? '', /^ik-workflow-transition-/)
const tokenParts = capturedTransition.authorization.slice('Bearer '.length).split('.')
assert.equal(tokenParts.length, 3, 'workflow bearer is not a JWT; cannot prove exact principal binding')
const tokenClaims = JSON.parse(Buffer.from(tokenParts[1], 'base64url').toString('utf8'))
assert.equal(tokenClaims.sub, cfg.expectedAssigneePrincipalId, 'agent credential JWT subject is not the exact assignee')

// CTR-009 acceptance assertions (B): response workflowStateVersion == V+1,
// eventSequence present, currentNodeVisitId != sourceNodeVisitId.
assert.equal(first.workflowStateVersion, cfg.expectedWorkflowStateVersion + 1, 'transition response workflowStateVersion is not V+1')
assert.ok(first.eventSequence !== undefined && first.eventSequence !== null, 'transition response eventSequence missing')
assert.ok(typeof first.currentNodeVisitId === 'string' && first.currentNodeVisitId !== '', 'transition response currentNodeVisitId missing')
assert.ok(typeof first.sourceNodeVisitId === 'string' && first.sourceNodeVisitId !== '', 'transition response sourceNodeVisitId missing')
assert.notEqual(first.currentNodeVisitId, first.sourceNodeVisitId, 'current and source node visits must differ after a transition')

const replayResponse = await realFetch(capturedTransition.url, {
  method: capturedTransition.method,
  headers: {
    Authorization: capturedTransition.authorization,
    'Idempotency-Key': capturedTransition.idempotencyKey,
    'Content-Type': capturedTransition.contentType,
    Accept: capturedTransition.accept,
  },
  body: capturedTransition.body,
  signal: AbortSignal.timeout(10000),
})
assert.equal(replayResponse.ok, true, `same-key replay failed with HTTP ${replayResponse.status}`)
const replayCopy = replayResponse.clone()
const replayBody = new Uint8Array(await replayCopy.arrayBuffer())
assert.equal(replayCopy.status, capturedTransition.firstStatus, 'same-key replay HTTP status differs')
assert.equal(replayCopy.headers.get('content-type'), capturedTransition.firstContentType, 'same-key replay content-type differs')
assert.deepEqual(replayBody, capturedTransition.firstBody, 'same-key replay raw response body differs')
const replay = await replayResponse.json()
assert.deepEqual(replay, first, 'same-key replay parsed response differs from first success')

// CTR-009 acceptance assertion (C): re-read the detail; version advanced and a
// new current node visit is visible.
const after = await detail(cfg.canaryInstanceId)
const afterVersion = after.workflow_state_version ?? after.workflowStateVersion
assert.equal(afterVersion, cfg.expectedWorkflowStateVersion + 1, 'detail re-read state version is not V+1')
const afterNodeVisitId = after.current_node_visit?.node_visit_id ?? after.current_node_visit?.id ?? after.currentNodeVisit?.nodeVisitId ?? after.currentNodeVisit?.id ?? null
assert.ok(typeof afterNodeVisitId === 'string' && afterNodeVisitId !== '', 'detail re-read current node visit missing')
if (beforeNodeVisitId) {
  assert.notEqual(afterNodeVisitId, beforeNodeVisitId, 'detail re-read current node visit did not change')
}

const controlAfter = await detail(cfg.controlInstanceId)
assert.deepEqual(controlAfter, controlBefore, 'non-canary control instance changed')
const domainAfter = await paginateDomain()
assert.deepEqual([...domainAfter.itemsById.keys()].sort(), [...domainBefore.itemsById.keys()].sort(), 'domain instance membership changed')
for (const [id, itemBefore] of domainBefore.itemsById) {
  if (id === cfg.canaryInstanceId) continue
  assert.deepEqual(domainAfter.itemsById.get(id), itemBefore, `other domain instance changed: ${id}`)
}

console.log(`CANARY_PAGINATION=PASS pages_before=${domainBefore.pages} pages_after=${domainAfter.pages} unique_instances=${domainBefore.itemsById.size} final_cursor=null`)
console.log(`CANARY_TRANSITION=PASS exact_assignee=${cfg.expectedAssigneePrincipalId} first_success=true state_version=${afterVersion} same_key_replay=identical all_other_instances_unchanged=true`)
NODE
  fsync_file "$output"
  fsync_directory "$(dirname "$output")"
}

# Post-reload combined smoke: workflow + forum normal + moderator visibility,
# asserted against the INSTALLED live files after the single reload. Zero
# mutation: no writes, no moderator tool invocation (forum.moderate grant may be
# unsupplied; authorization_denied at call time is the expected fail-closed
# state and must never roll back the normal deployment — so this smoke never
# calls moderator tools, it proves the registration seam instead).
write_smoke_program() {
  local output="$1"
  cat > "$output" <<'NODE'
import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'

const [appRoot, credentialsFile, authOrigin, configPath] = process.argv.slice(2)
let cfg = {}
try { cfg = JSON.parse(await readFile(configPath, 'utf8')) } catch { cfg = {} }

const WORKFLOW_ALL = ['workflow_my_tasks','workflow_instance_detail','workflow_submission_history','workflow_my_domains','workflow_domain_instances','workflow_global_instances','workflow_transition']
const FORUM_EXISTING = ['forum_my_notifications','forum_read_thread','forum_read_transcript','forum_reply','forum_mark_read','forum_list_threads','forum_search_threads']
const FORUM_NORMAL_NEW = ['forum_create_thread','forum_watch_thread','forum_unwatch_thread','forum_report_content','forum_stats']
const MODERATOR_ALL = ['forum_pin_or_feature_thread','forum_delete_thread','forum_delete_message','forum_resolve_thread','forum_archive_thread','forum_moderation_queue','forum_handle_report','forum_admin_unread']
const MODERATOR_AGENT = 'agt_course-community-agent-2'

const url = (p) => pathToFileURL(`${appRoot}/${p}`)
const [{ manifests: workflowManifests }, { manifests: forumManifests, normalManifests }, { moderatorManifests }, { DEFAULT_MANIFESTS, resolveForumModeratorRegistration }] = await Promise.all([
  import(url('packages/broker/src/capabilities/workflow.js')),
  import(url('packages/broker/src/capabilities/forum.js')),
  import(url('packages/broker/src/capabilities/forum-moderation.js')),
  import(url('packages/broker/src/index.js')),
])

// ── Workflow visibility ───────────────────────────────────────────────────
const wfIds = new Set(workflowManifests.map((m) => m.id))
for (const id of WORKFLOW_ALL) assert.ok(wfIds.has(id), `workflow manifest missing: ${id}`)
const transition = workflowManifests.find((m) => m.id === 'workflow_transition')
const submit = transition.operations.find((op) => op.name === 'submit')
assert.ok(submit?.http && submit.http.method === 'POST' && /transitions/.test(String(submit.http.path)), 'workflow_transition submit POST binding missing')
assert.equal(submit.http.idempotencyKey, true, 'workflow_transition submit must declare idempotencyKey')
console.log(`SMOKE_WORKFLOW=PASS visible=${WORKFLOW_ALL.length} transition_submit=post+idempotent domain_instances=visible global_instances=visible`)

// ── Forum normal visibility (CTR-FMC-002 exact pack and scopes) ───────────
const forumIds = new Set(forumManifests.map((m) => m.id))
for (const id of FORUM_EXISTING) assert.ok(forumIds.has(id), `existing forum manifest missing (regression): ${id}`)
const normalIds = new Set(normalManifests.map((m) => m.id))
assert.equal(normalIds.size, 5, 'forum normal pack must contain exactly 5 manifests')
for (const id of FORUM_NORMAL_NEW) assert.ok(normalIds.has(id), `forum normal pack manifest missing: ${id}`)
for (const m of normalManifests) {
  const expected = m.id === 'forum_stats' ? ['forum.read'] : ['forum.write']
  assert.deepEqual(m.requiredScopes, expected, `forum normal manifest scopes wrong: ${m.id}`)
}
console.log(`SMOKE_FORUM_NORMAL=PASS existing_7=invariant create=visible watch=visible unwatch=visible report=visible stats=visible`)

// ── Moderator visibility (CTR-FMC-003/004): only the closed-list agent ────
assert.equal(moderatorManifests.length, 8, 'moderator pack must contain exactly 8 manifests')
const modIds = new Set(moderatorManifests.map((m) => m.id))
for (const id of MODERATOR_ALL) assert.ok(modIds.has(id), `moderator manifest missing: ${id}`)
for (const m of moderatorManifests) {
  assert.deepEqual(m.requiredScopes, ['forum.read', 'forum.write', 'forum.moderate'], `moderator manifest scopes wrong: ${m.id}`)
}
const memberCfg = { forumModeratorAgentIds: [MODERATOR_AGENT] }
const asMember = resolveForumModeratorRegistration(memberCfg, { DSH_AGENT_ID: MODERATOR_AGENT })
assert.equal(asMember.manifests.length, 8, 'closed-list member must register all 8 moderator tools')
const asOther = resolveForumModeratorRegistration(memberCfg, { DSH_AGENT_ID: 'agt_cto-agent' })
assert.equal(asOther.manifests.length, 0, 'non-member agent must register zero moderator tools')
const asNoEnv = resolveForumModeratorRegistration(memberCfg, {})
assert.equal(asNoEnv.manifests.length, 0, 'absent DSH_AGENT_ID must register zero moderator tools')
const asEmptyList = resolveForumModeratorRegistration({ forumModeratorAgentIds: [] }, { DSH_AGENT_ID: MODERATOR_AGENT })
assert.equal(asEmptyList.manifests.length, 0, 'empty moderator list must fail closed')
const asBadList = resolveForumModeratorRegistration({ forumModeratorAgentIds: ['not-agt'] }, { DSH_AGENT_ID: MODERATOR_AGENT })
assert.equal(asBadList.manifests.length, 0, 'malformed moderator list must fail closed')

// The deployed bundle config itself must carry exactly the closed list.
const patchYml = await readFile(`${appRoot}/bundle-broker/cordis.patch.yml`, 'utf8')
const listMatch = patchYml.match(/forumModeratorAgentIds:\s*\[([^\]]*)\]/)
assert.ok(listMatch, 'bundle-broker/cordis.patch.yml lacks forumModeratorAgentIds')
const configured = listMatch[1].split(',').map((s) => s.trim().replace(/^['"]|['"]$/g, '')).filter((s) => s !== '')
assert.deepEqual(configured, [MODERATOR_AGENT], 'bundle moderator list must equal exactly [agt_course-community-agent-2]')

// Default registration surface: every child sees the packs; no moderator tool
// is default-registered anywhere.
const defaultIds = new Set(DEFAULT_MANIFESTS.map((m) => m.id))
for (const id of [...WORKFLOW_ALL, ...FORUM_EXISTING, ...FORUM_NORMAL_NEW]) {
  assert.ok(defaultIds.has(id), `DEFAULT_MANIFESTS missing tool: ${id}`)
}
for (const id of MODERATOR_ALL) {
  assert.equal(defaultIds.has(id), false, `moderator tool must not be default-registered: ${id}`)
}
console.log(`SMOKE_MODERATOR=PASS pack=8 member=${MODERATOR_AGENT} non_member=0 absent_env=0 malformed_list=fail_closed bundle_config=exact forum_moderate_grant=not_probed_by_design`)

// ── Optional forum wire smoke (read-only; only when the canary config
// supplies a forum-capable identity). Never mutates forum state.
if (typeof cfg.forumSmokeAgentId === 'string' && cfg.forumSmokeAgentId.startsWith('agt_')) {
  const [{ createBrokerGateway }, { targets }] = await Promise.all([
    import(url('packages/broker/src/gateway.js')),
    import(url('packages/broker/src/targets.js')),
  ])
  const gateway = createBrokerGateway({ manifests: [...forumManifests, ...normalManifests], targets, authServiceOrigin: authOrigin, credentialsFile })
  const exec = async (capabilityId, operation, args) => {
    const out = await gateway.execute({ capabilityId, operation, args }, { agentId: cfg.forumSmokeAgentId })
    assert.equal(out?.ok, true, `${capabilityId}.${operation} failed: ${JSON.stringify(out?.error ?? out)}`)
    return out.result
  }
  const listed = await exec('forum_list_threads', 'list', {})
  const threads = Array.isArray(listed?.items) ? listed.items : (Array.isArray(listed) ? listed : [])
  await exec('forum_search_threads', 'search', { q: 'combined-deploy-smoke-probe' })
  let readOk = 0
  if (threads.length > 0) {
    const firstId = threads[0].thread_id ?? threads[0].threadId ?? threads[0].id
    if (firstId) { await exec('forum_read_thread', 'read', { threadId: firstId }); readOk = 1 }
  }
  console.log(`FORUM_WIRE_SMOKE=PASS list=ok search=ok read=${readOk === 1 ? 'ok' : 'skipped_no_thread'} reply=registration_only_by_design agent=${cfg.forumSmokeAgentId}`)
} else {
  console.log('FORUM_WIRE_SMOKE=SKIPPED_NO_IDENTITY (config lacks forumSmokeAgentId; registration surface fully verified)')
}
NODE
  fsync_file "$output"
  fsync_directory "$(dirname "$output")"
}

# Durable receipt template (authoring artifact). Static fields are literal;
# @VAR@ placeholders are substituted at receipt time (sed), then validated as
# JSON before it becomes durable.
write_receipt_template() {
  local output="$1"
  cat > "$output" <<'EOF'
{
  "receipt": "AGENT_CORE_COMBINED_DEPLOY_V1",
  "created_utc": "@TS@",
  "runner": "/tmp/run-agent-core-combined-deploy-v2.sh",
  "runner_sha256": "@RUNNER_SHA@",
  "target_main": "2392a41d4655ba25ed9e9749fbf8beb0ad1c71b4",
  "merged_authority": {
    "workflow_transition": {"spec": "AGENT_CORE_WORKFLOW_ASSIGNEE_TRANSITION_CAPABILITY_V1", "merge": "1aa8248893766aaf1caae17b2905e40061f0a147", "pr": 125},
    "domain_pagination": {"spec": "AGENT_CORE_WORKFLOW_DOMAIN_INSTANCES_PAGINATION_V2", "merge": "4d7ca245ec0b9f6ed8a650f742b94b39728331a7", "pr": 126},
    "error_preservation": {"spec": "AGENT_CORE_WORKFLOW_BROKER_ERROR_PRESERVATION_V1", "note": "family discipline; own implementation already deployed at PR #82; V2 sanitizer restated by CTR-FMC-12"},
    "forum_moderation": {"spec": "AGENT_CORE_FORUM_MODERATION_CAPABILITIES_V2", "merge": "2392a41d4655ba25ed9e9749fbf8beb0ad1c71b4", "impl_head": "83165dea530956a8836e9830c54811eb3a8ae93e", "pr": 105}
  },
  "base_manifest": {"count": 132, "sha256": "9ac84954fefc3d5893b7e5ca7045b2bb7cf0ad7492d121607d2b0659a230f4b1"},
  "target_manifest": {"count": 134, "sha256": "865b6569591e361b18ffcde01251c0b2c2ba160818a0738127a2e8a0bcf2a8d6"},
  "delta": [
    {"path": "packages/broker/src/capabilities/workflow.js", "base": "04ca8550fbdaf9b66624dea42701a8a9af7547a8", "target": "83df50eb9947c865a2df531b05285c5e0f3eae0c"},
    {"path": "packages/broker/src/mapping.js", "base": "890d35b97700e741b0b6960049b619da03645483", "target": "74e83e11660a0ea5a9dffc47fe2a8897f17f9809"},
    {"path": "packages/broker/src/schema.js", "base": "13f80f87ce3591669224a061a243fa6cce96a553", "target": "1bd36bbe5f3fc796dffdf633b557fbb7fff2741b"},
    {"path": "packages/broker/src/capabilities/forum.js", "base": "f068c171c2c8bd66b774c197bdbae09d1bcf809b", "target": "b64b73578f9645777025d8bff74e82f551de3866"},
    {"path": "packages/broker/src/capabilities/forum-moderation.js", "base": "ABSENT", "target": "90cf87c3e4afd424574b4f18b12742306c5968df"},
    {"path": "packages/broker/src/error-detail-sanitizer.js", "base": "ABSENT", "target": "25e02239255f95c55e59454bd32703550e3ad5b0"},
    {"path": "packages/broker/src/index.js", "base": "6c4a60af4c529dd052ad45bd641213d40ee6800c", "target": "a543e586792aa18c592b7d2afb535b4ff575d286"},
    {"path": "packages/broker/src/transport.js", "base": "b697850cfd1961ac7ee88aa625d0a5c711aa7eac", "target": "942e9880ff11fbc672481f66f7e96d35778dfc4f"},
    {"path": "bundle-broker/cordis.patch.yml", "base": "b84c629679e900ea886896c9656c8ecb9fb792ae", "target": "768ddecaea5fedabe3c44cb63c11926cdfb2b885", "note": "outside app manifest (bundle-* pruned); pinned by blob OID; enters production via the normal bundle build flow"}
  ],
  "excluded_drift_untouched": [
    {"path": "packages/production-runtime/src/model-overrides.js", "live": "ea44819a18085c6bd8665157d92caba205e720d9", "reason": "emergency breakglass pending Owner ratification"},
    {"path": "packages/feishu-connector/src/index.js", "live": "2e6bd0896dd0354877aebc99361a986a05c1e06a", "reason": "unauthorized 9386ac4 feishu delta; no deployment authority"},
    {"path": "packages/scheduler-router/src/index.js", "live": "b1f5563411cb55c8ddc3391d6337a30aea2e0f45", "reason": "unauthorized 9386ac4 scheduler delta; no deployment authority"}
  ],
  "canary_config": {"path": "/tmp/agent-core-workflow-canary-v1.json", "sha256": "@CANARY_SHA@", "identity": "agt_build-in-public-agent (CTR-009)"},
  "canary": "@CANARY_SUMMARY@",
  "smoke": "@SMOKE_SUMMARY@",
  "reload": {"target": "system/ai.agent-core.runtime", "count": 1},
  "backup_path": "@BACKUP@"
}
EOF
  fsync_file "$output"
  fsync_directory "$(dirname "$output")"
}

run_check() {
  verify_source_authority
  verify_tree "$LIVE_ROOT" EITHER
  service_preflight
  validate_canary_prereqs
  echo "LIVE_MANIFEST=$BASE_FILE_COUNT/$BASE_MANIFEST_SHA256 state=$DETECTED_STATE"
  echo "DEPLOYMENT_DELTA=$DELTA_COUNT files (7 modified + 2 new; 8 in-manifest + 1 bundle config) iff state=BASE; 0 iff state=TARGET"
  echo "BREAKGLASS=$BREAKGLASS_PATH@$BREAKGLASS_OID pinned-never-written"
  echo "EXCLUDED_DRIFT=$(line_at "$EXCLUDED_PIN_PATHS" 1)@$(line_at "$EXCLUDED_PIN_OIDS" 1) $(line_at "$EXCLUDED_PIN_PATHS" 2)@$(line_at "$EXCLUDED_PIN_OIDS" 2) (unauthorized 9386ac4; pinned-never-written)"
  echo "TARGET_MAIN=$TARGET_COMMIT contains=$TRANSITION_MERGE,$PAGINATION_MERGE,$FORUM_MERGE (forum impl head $FORUM_IMPL_HEAD)"
  if [ "$CANARY_CONFIG_SHA256" != "" ]; then
    echo "CANARY_CONFIG=$CANARY_CONFIG sha256=$CANARY_CONFIG_SHA256"
  fi
  if [ "$CANARY_READY" != "YES" ]; then
    echo "CHECK=FAIL (canary prerequisites not ready; apply is refused)"
    exit 2
  fi
  echo "CHECK=PASS"
}

run_apply() {
  local config_sha="$1"
  [ "$(/usr/bin/id -u)" = "0" ] || fail "--apply requires uid 0; runner never invokes sudo"
  [[ "$config_sha" =~ ^[0-9a-f]{64}$ ]] || fail "--apply takes the canary config sha256 printed by --check"
  validate_canary_prereqs
  [ "$CANARY_READY" = "YES" ] || fail "CANARY_PREREQS_READY=$CANARY_READY; apply refused (zero writes)"
  [ "$CANARY_CONFIG_SHA256" = "$config_sha" ] \
    || fail "canary config sha pin mismatch: reviewed=$config_sha actual=$CANARY_CONFIG_SHA256 (zero writes)"
  verify_source_authority
  verify_tree "$LIVE_ROOT" EITHER
  service_preflight
  if [ "$DETECTED_STATE" = "TARGET" ]; then
    echo "APPLY=NOOP_ALREADY_TARGET (zero files, zero reloads, zero canary mutation)"
    exit 0
  fi
  echo "Will durably install exactly $DELTA_COUNT files (7 modified + 2 new + bundle moderator config), pin the breakglass and both unauthorized drift files untouched, run the post-deploy workflow transition canary, then reload $SERVICE_LABEL exactly once on success."
  printf 'Type the phrase "%s" to proceed: ' "$CONFIRM_PHRASE"
  local answer=""; read -r answer
  [ "$answer" = "$CONFIRM_PHRASE" ] || fail "confirmation mismatch (zero writes)"

  local lock ts backup stage canary smoke path p mode uid gid actual i rc rollback_ok runner_sha
  lock="$TRUSTED_ROOT/.deploy-combined-v2.lock"
  ts="$(/bin/date -u +%Y%m%dT%H%M%SZ)"
  backup="$BACKUP_ROOT/agent-core-combined-v1-$ts"
  stage=""
  APPLY_WRITES=0; LOCK_CREATED=0; STAGE_CREATED=0; RESTART_COUNT=0
  /bin/mkdir "$lock" || fail "deploy lock exists: $lock"
  LOCK_CREATED=1; fsync_directory "$TRUSTED_ROOT"

  cleanup_apply() {
    rc="$1"; trap - EXIT; trap '' INT TERM; rollback_ok=1
    if [ "$rc" -ne 0 ] && [ "$APPLY_WRITES" = "1" ]; then
      echo "ERROR: apply failed (rc=$rc); durable rollback begins" >&2
      i=1
      while [ "$i" -le "$DELTA_COUNT" ]; do
        path="$(line_at "$DELTA_PATHS" "$i")"; p="$LIVE_ROOT/$path"
        if [ "$(line_at "$BASE_OIDS" "$i")" = "ABSENT" ]; then
          if [ -e "$p" ] || [ -L "$p" ]; then
            /bin/rm -f "$p" || rollback_ok=0
            fsync_directory "$(dirname "$p")" || rollback_ok=0
          fi
        else
          mode="$(/usr/bin/stat -f '%Lp' "$p" 2>/dev/null || echo 644)"
          uid="$(/usr/bin/stat -f '%u' "$p" 2>/dev/null || echo 0)"
          gid="$(/usr/bin/stat -f '%g' "$p" 2>/dev/null || echo 0)"
          atomic_install "$backup/$path" "$p" "$mode" "$uid" "$gid" || rollback_ok=0
        fi
        i=$((i + 1))
      done
      verify_tree_status "$LIVE_ROOT" && [ "$DETECTED_STATE" = "BASE" ] || rollback_ok=0
      if [ "$RESTART_COUNT" -gt 0 ]; then
        echo "NOTICE: rollback reload required after the success-path reload" >&2
        /bin/launchctl kickstart -k "$SERVICE_LABEL" && wait_for_health || rollback_ok=0
      fi
      if [ "$rollback_ok" = "1" ]; then
        echo "ROLLBACK=OK (all files and parents fsynced; BASE restored)"
      else
        echo "ERROR: ROLLBACK_INCOMPLETE backup=$backup lock=$lock" >&2
        exit 3
      fi
    fi
    [ "$STAGE_CREATED" = "0" ] || /bin/rm -rf "$stage" || rollback_ok=0
    if [ "$LOCK_CREATED" = "1" ]; then /bin/rmdir "$lock" || rollback_ok=0; fsync_directory "$TRUSTED_ROOT" || rollback_ok=0; fi
    [ "$rollback_ok" = "1" ] || exit 3
    exit "$rc"
  }
  trap 'cleanup_apply "$?"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM

  /bin/mkdir -p "$backup"
  i=1
  while [ "$i" -le "$DELTA_COUNT" ]; do
    path="$(line_at "$DELTA_PATHS" "$i")"
    if [ "$(line_at "$BASE_OIDS" "$i")" != "ABSENT" ]; then
      /bin/mkdir -p "$backup/$(dirname "$path")"
      /bin/cp -p "$LIVE_ROOT/$path" "$backup/$path"
      actual="$(hash_file "$backup/$path")"
      [ "$actual" = "$(line_at "$BASE_OIDS" "$i")" ] || fail "backup mismatch: $path"
      fsync_file "$backup/$path"
      fsync_directory_chain "$backup/$(dirname "$path")" "$backup"
    fi
    i=$((i + 1))
  done
  runner_sha="$("$SHASUM" -a 256 "$0" | /usr/bin/awk '{print $1}')"
  cat > "$backup/README.txt" <<EOF
agent-core COMBINED deploy backup (Workflow delta + Forum moderation delta)
target_commit=$TARGET_COMMIT
transition_merge=$TRANSITION_MERGE
pagination_merge=$PAGINATION_MERGE
forum_merge=$FORUM_MERGE (impl head $FORUM_IMPL_HEAD)
base_manifest=$BASE_FILE_COUNT/$BASE_MANIFEST_SHA256
target_manifest=$TARGET_FILE_COUNT/$TARGET_MANIFEST_SHA256
delta_paths=$DELTA_COUNT (new files removed on rollback: packages/broker/src/capabilities/forum-moderation.js, packages/broker/src/error-detail-sanitizer.js)
breakglass=$BREAKGLASS_PATH@$BREAKGLASS_OID never-written
excluded_pinned=$(line_at "$EXCLUDED_PIN_PATHS" 1)@$(line_at "$EXCLUDED_PIN_OIDS" 1) $(line_at "$EXCLUDED_PIN_PATHS" 2)@$(line_at "$EXCLUDED_PIN_OIDS" 2) never-written
canary_config=$CANARY_CONFIG sha256=$CANARY_CONFIG_SHA256
runner=/tmp/run-agent-core-combined-deploy-v2.sh sha256=$runner_sha
created_utc=$ts
EOF
  fsync_file "$backup/README.txt"
  fsync_directory "$backup"
  fsync_directory "$BACKUP_ROOT"

  stage="$(/usr/bin/mktemp -d "$TRUSTED_ROOT/.deploy-combined-v2-stage.XXXXXX")"
  STAGE_CREATED=1; fsync_directory "$TRUSTED_ROOT"
  i=1
  while [ "$i" -le "$DELTA_COUNT" ]; do
    path="$(line_at "$DELTA_PATHS" "$i")"
    "$GIT" -C "$REPO_ROOT" show "$TARGET_COMMIT:$path" > "$stage/file-$i"
    [ "$(hash_file "$stage/file-$i")" = "$(line_at "$TARGET_OIDS" "$i")" ] || fail "staged blob mismatch: $path"
    fsync_file "$stage/file-$i"
    i=$((i + 1))
  done
  canary="$stage/canary.mjs"; write_canary_program "$canary"
  smoke="$stage/smoke.mjs"; write_smoke_program "$smoke"
  write_receipt_template "$stage/receipt.template"

  APPLY_WRITES=1
  i=1
  while [ "$i" -le "$DELTA_COUNT" ]; do
    path="$(line_at "$DELTA_PATHS" "$i")"; p="$LIVE_ROOT/$path"
    if [ "$(line_at "$BASE_OIDS" "$i")" = "ABSENT" ]; then
      atomic_install "$stage/file-$i" "$p" 644 0 0
    else
      mode="$(/usr/bin/stat -f '%Lp' "$p")"; uid="$(/usr/bin/stat -f '%u' "$p")"; gid="$(/usr/bin/stat -f '%g' "$p")"
      atomic_install "$stage/file-$i" "$p" "$mode" "$uid" "$gid"
    fi
    i=$((i + 1))
  done
  verify_tree "$LIVE_ROOT" TARGET

  echo "== post-deploy workflow transition canary against installed files (before the sole reload)"
  "$NODE" "$canary" "$LIVE_ROOT" "$CREDENTIALS_FILE" "$AUTH_ORIGIN" "$WORKFLOW_ORIGIN" "$CANARY_CONFIG" 2>&1 | /usr/bin/tee "$stage/canary.out"
  verify_tree "$LIVE_ROOT" TARGET

  echo "== sole success-path reload: $SERVICE_LABEL"
  RESTART_COUNT=1
  /bin/launchctl kickstart -k "$SERVICE_LABEL" || { echo "ERROR: runtime reload failed" >&2; exit 1; }
  [ "$RESTART_COUNT" = "1" ] || { echo "ERROR: reload count invariant violated" >&2; exit 1; }
  wait_for_health || { echo "ERROR: health failed after reload" >&2; exit 1; }
  /bin/launchctl print "$SERVICE_LABEL" >/dev/null 2>&1 || { echo "ERROR: launchd status failed" >&2; exit 1; }
  verify_tree "$LIVE_ROOT" TARGET

  echo "== post-reload combined smoke (workflow + forum normal + moderator visibility)"
  "$NODE" "$smoke" "$LIVE_ROOT" "$CREDENTIALS_FILE" "$AUTH_ORIGIN" "$CANARY_CONFIG" 2>&1 | /usr/bin/tee "$stage/smoke.out"
  verify_tree "$LIVE_ROOT" TARGET

  echo "== durable receipt"
  local canary_summary smoke_summary
  canary_summary="$(/usr/bin/grep -E '^[A-Z_]+=' "$stage/canary.out" | /usr/bin/tr '\n' ';' | /usr/bin/sed 's/;*$//')"
  smoke_summary="$(/usr/bin/grep -E '^[A-Z_]+=' "$stage/smoke.out" | /usr/bin/tr '\n' ';' | /usr/bin/sed 's/;*$//')"
  /usr/bin/sed -e "s#@RUNNER_SHA@#$runner_sha#" -e "s#@TS@#$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ)#" \
    -e "s#@BACKUP@#$backup#" -e "s#@CANARY_SHA@#$CANARY_CONFIG_SHA256#" \
    -e "s#@CANARY_SUMMARY@#$canary_summary#" \
    -e "s#@SMOKE_SUMMARY@#$smoke_summary#" \
    "$stage/receipt.template" > "$backup/receipt.json"
  "$PYTHON3" - "$backup/receipt.json" <<'PY'
import json, sys
with open(sys.argv[1]) as fh:
    json.load(fh)
PY
  fsync_file "$backup/receipt.json"
  fsync_directory "$backup"
  printf '%s\n' "$(/bin/date -u +%Y-%m-%dT%H:%M:%SZ) applied target=$TARGET_COMMIT backup=$backup manifest=$TARGET_MANIFEST_SHA256 delta=combined-v2-9files canary=pass smoke=pass reload_count=1 breakglass=$BREAKGLASS_OID canary_config_sha256=$CANARY_CONFIG_SHA256 receipt=$backup/receipt.json" >> "$LEDGER"
  fsync_file "$LEDGER"; fsync_directory "$BACKUP_ROOT"
  # The durable receipt + ledger are the commit point. From here onward cleanup
  # failure must retain TARGET (and possibly its lock), never roll back into a
  # false receipt.
  APPLY_WRITES=0
  /bin/rm -rf "$stage"; STAGE_CREATED=0; fsync_directory "$TRUSTED_ROOT"
  /bin/rmdir "$lock"; LOCK_CREATED=0; fsync_directory "$TRUSTED_ROOT"
  trap - EXIT INT TERM
  echo "SUCCESS_COMMITTED target=$TARGET_COMMIT reload_count=1 breakglass_untouched=true excluded_drift_untouched=true"
  echo "BACKUP_PATH=$backup"
  echo "RECEIPT_PATH=$backup/receipt.json"
  echo "APPLY=PASS"
}

usage() {
  cat <<'EOF'
Usage:
  bash /tmp/run-agent-core-combined-deploy-v2.sh --check
  bash /tmp/run-agent-core-combined-deploy-v2.sh --apply <canary-config-sha256-from-check>

ONE DEPLOY + ONE RELOAD carrying the pending accepted Workflow Broker delta
(workflow_transition + domain pagination successor + error-preservation
discipline) AND the freshly merged Forum moderation delta (PR #105) at
TARGET_MAIN=2392a41d4655ba25ed9e9749fbf8beb0ad1c71b4.

Canary prerequisite (fail closed): /tmp/agent-core-workflow-canary-v1.json
(generated by the separate canary-prep task) must exist, parse as JSON, carry
no placeholder and no secret, pin exact baselines, and use the accepted
CTR-009 canary identity `agt_build-in-public-agent`. --check prints
CANARY_CONFIG_SHA256 and CANARY_PREREQS_READY; if readiness is not YES,
--check exits 2 and --apply refuses before any write. --apply takes the
CANARY_CONFIG_SHA256 printed by --check and refuses on any byte mismatch
(reviewed config == applied config).

Optional config field: forumSmokeAgentId (agt_* identity with forum.read) —
when present the post-reload smoke additionally performs read-only forum
list/search/read wire calls; otherwise the registration surface is verified
without wire calls. Moderator tools are never invoked by this runner: the
forum.moderate grant may be unsupplied (authorization_denied is the expected
fail-closed state and never rolls back the normal deployment), so the
moderator proof is the CTR-FMC-004 registration seam plus the deployed
bundle-broker moderator list.

The runner never invokes sudo. --check is read-only. --apply requires uid 0
and an interactive phrase. model-overrides.js (breakglass),
feishu-connector/src/index.js and scheduler-router/src/index.js (unauthorized
9386ac4 drift) are pinned at their live OIDs and NEVER written; any drift in
either direction refuses all writes.
EOF
}

case "${1:-}" in
  --check) [ "$#" = "1" ] || { usage >&2; exit 2; }; run_check ;;
  --apply) [ "$#" = "2" ] || { usage >&2; exit 2; }; run_apply "$2" ;;
  -h|--help) usage ;;
  *) usage >&2; exit 2 ;;
esac
